SECTION .text
GLOBAL test
test:
jmp rax
jmp rbx
jmp rcx
jmp rdx
jmp rdi
jmp r8
jmp r9
jmp r10
jmp r11
jmp r12
jmp r13
jmp r14
jmp r15
jmp rsp
jmp rsi
jmp rbp
jmp [rax]
jmp [rbx]
jmp [rcx]
jmp [rdx]
jmp [rdi+0x7f]
jmp [r8]
jmp [r9]
jmp [r10]
jmp [r11]
jmp [r12+0x7fff]
jmp [r13]
jmp [r14+0x7fffffff]
jmp [r15]
jmp [rsp]
jmp [rsi]
jmp [rbp]
jmp far [rbp]
jmp far [rax]
jmp far [rbx]
jmp far [rcx]
jmp far [rdx]
jmp far [ebp]
jmp far [eax]
jmp far [ebx]
jmp far [ecx]
jmp far [edx]
jmp far [edx]
jmp far [rdi+0x7f]
jmp far [r8]
jmp far [r9]
jmp far [r10]
jmp far [r11]
jmp far [r12+0x7fff]
jmp far [r13]
jmp far [r14+0x7fffffff]
jmp far [r15]
jmp far [rsp]
jmp far [rsi]
jmp far dword [rbp]
jmp far dword [rax]
jmp far dword [rbx]
jmp far dword [rcx]
jmp far dword [rdx]
jmp far dword [ebp]
jmp far dword [eax]
jmp far dword [ebx]
jmp far dword [ecx]
jmp far dword [edx]
jmp far dword [edx]
jmp far dword [rdi+0x7f]
jmp far dword [r8]
jmp far dword [r9]
jmp far dword [r10]
jmp far dword [r11]
jmp far dword [r12+0x7fff]
jmp far dword [r13]
jmp far dword [r14+0x7fffffff]
jmp far dword [r15]
jmp far dword [rsp]
jmp far dword [rsi]
jmp far word [rbp]
jmp far word [rax]
jmp far word [rbx]
jmp far word [rcx]
jmp far word [rdx]
jmp far word [ebp]
jmp far word [eax]
jmp far word [ebx]
jmp far word [ecx]
jmp far word [edx]
jmp far word [edx]
jmp far word [rdi+0x7f]
jmp far word [r8]
jmp far word [r9]
jmp far word [r10]
jmp far word [r11]
jmp far word [r12+0x7fff]
jmp far word [r13]
jmp far word [r14+0x7fffffff]
jmp far word [r15]
jmp far word [rsp]
jmp far word [rsi]
jmp [0x7f]
jmp far [0x7fff]
jmp far [0x7fffffff]
jmp far word [0x7fffffff]
jmp far [0x1234567812121212]
jmp far dword [0x1234567812121212]
jmp far [-1]
jmp far [-0x4]
jmp far [0x7f]
jmp far [0x7fff]
jmp far [0x7fffffff]
jmp far qword [0x1234567812121212]