SECTION .text
GLOBAL test
test:
lea rax, [rax+3]
lea rax, [rax+0x3]
lea rax, [rax+0x1]
lea r10, [ r10 + r15 ]
lea r11, [ r11 + r12 ]
lea r13, [ r13 + rbx ]
lea r14, [ r14 + r12 ]
lea r14, [ r14 + r13 ]
lea r14, [ r14 + rax ]
lea r9, [ r9 + r8 ]
lea rax, [ rax + r10 ]
lea rax, [ rax + r11 ]
lea rax, [ rax + r14 ]
lea rax, [ rax + r9 ]
lea rax, [ rax + rcx ]
lea rax, [ rax + rcx ]
lea rbp, [ rbp + r10 ]
lea rbp, [ rbp + rdx ]
lea rbx, [ rbx + r12 ]
lea rbx, [ rbx + r12 ]
lea rbx, [ rbx + rdx ]
lea rcx, [ rcx + r11 ]
lea rdx, [ rdx + r13 ]

lea rax, [rax + rax]
lea rax, [rax + rbx]
lea rax, [rax + rcx]
lea rax, [rax + rdx]
lea rax, [rax + rdi]
lea rax, [rax + r8]
lea rax, [rax + r9]
lea rax, [rax + r10]
lea rax, [rax + r11]
lea rax, [rax + r12]
lea rax, [rax + r13]
lea rax, [rax + r14]
lea rax, [rax + r15]
lea rax, [rsp + rax]
lea rax, [rax + rsi]
lea rax, [rax + rbp]
lea rax, [rbx + rax]
lea rax, [rbx + rbx]
lea rax, [rbx + rcx]
lea rax, [rbx + rdx]
lea rax, [rbx + rdi]
lea rax, [rbx + r8]
lea rax, [rbx + r9]
lea rax, [rbx + r10]
lea rax, [rbx + r11]