name: 'AssemblyLine'
description: 'Will install dependencies to build AssemblyLine, build and install AssemblyLine.'

runs:
  using: "composite"
  steps:
    - uses: actions/checkout@v3
      with:
        repository: 0xADE1A1DE/AssemblyLine
        ref: v1.2.2

    - name: Install dependencies
      shell: bash
      run: sudo apt install -y autoconf curl gcc libtool make nasm pkg-config tar

    - name: Run autogen
      shell: bash
      run: ./autogen.sh

    - name: Run Configure
      shell: bash
      run: ./configure CFLAGS=-O3

    - name: Build
      shell: bash
      run: make all

    - name: install
      shell: bash
      run: sudo make install && ldconfig
