#define CODE                                                                                                           \
    "paddq xmm0, xmm0;\n"                                                                                              \
    "paddq xmm0, xmm1;\n"                                                                                              \
    "paddq xmm0, xmm2;\n"                                                                                              \
    "paddq xmm0, xmm3;\n"                                                                                              \
    "paddq xmm0, xmm4;\n"                                                                                              \
    "paddq xmm0, xmm5;\n"                                                                                              \
    "paddq xmm0, xmm6;\n"                                                                                              \
    "paddq xmm0, xmm7;\n"                                                                                              \
    "paddq xmm0, xmm8;\n"                                                                                              \
    "paddq xmm0, xmm9;\n"                                                                                              \
    "paddq xmm0, xmm10;\n"                                                                                             \
    "paddq xmm0, xmm11;\n"                                                                                             \
    "paddq xmm0, xmm12;\n"                                                                                             \
    "paddq xmm0, xmm13;\n"                                                                                             \
    "paddq xmm0, xmm14;\n"                                                                                             \
    "paddq xmm0, xmm15;\n"                                                                                             \
    ";\n"                                                                                                              \
    "paddq xmm1, xmm0;\n"                                                                                              \
    "paddq xmm1, xmm1;\n"                                                                                              \
    "paddq xmm1, xmm2;\n"                                                                                              \
    "paddq xmm1, xmm3;\n"                                                                                              \
    "paddq xmm1, xmm4;\n"                                                                                              \
    "paddq xmm1, xmm5;\n"                                                                                              \
    "paddq xmm1, xmm6;\n"                                                                                              \
    "paddq xmm1, xmm7;\n"                                                                                              \
    "paddq xmm1, xmm8;\n"                                                                                              \
    "paddq xmm1, xmm9;\n"                                                                                              \
    "paddq xmm1, xmm10;\n"                                                                                             \
    "paddq xmm1, xmm11;\n"                                                                                             \
    "paddq xmm1, xmm12;\n"                                                                                             \
    "paddq xmm1, xmm13;\n"                                                                                             \
    "paddq xmm1, xmm14;\n"                                                                                             \
    "paddq xmm1, xmm15;\n"                                                                                             \
    ";\n"                                                                                                              \
    "paddq xmm2, xmm0;\n"                                                                                              \
    "paddq xmm2, xmm1;\n"                                                                                              \
    "paddq xmm2, xmm2;\n"                                                                                              \
    "paddq xmm2, xmm3;\n"                                                                                              \
    "paddq xmm2, xmm4;\n"                                                                                              \
    "paddq xmm2, xmm5;\n"                                                                                              \
    "paddq xmm2, xmm6;\n"                                                                                              \
    "paddq xmm2, xmm7;\n"                                                                                              \
    "paddq xmm2, xmm8;\n"                                                                                              \
    "paddq xmm2, xmm9;\n"                                                                                              \
    "paddq xmm2, xmm10;\n"                                                                                             \
    "paddq xmm2, xmm11;\n"                                                                                             \
    "paddq xmm2, xmm12;\n"                                                                                             \
    "paddq xmm2, xmm13;\n"                                                                                             \
    "paddq xmm2, xmm14;\n"                                                                                             \
    "paddq xmm2, xmm15;\n"                                                                                             \
    ";\n"                                                                                                              \
    "paddq xmm3, xmm0;\n"                                                                                              \
    "paddq xmm3, xmm1;\n"                                                                                              \
    "paddq xmm3, xmm2;\n"                                                                                              \
    "paddq xmm3, xmm3;\n"                                                                                              \
    "paddq xmm3, xmm4;\n"                                                                                              \
    "paddq xmm3, xmm5;\n"                                                                                              \
    "paddq xmm3, xmm6;\n"                                                                                              \
    "paddq xmm3, xmm7;\n"                                                                                              \
    "paddq xmm3, xmm8;\n"                                                                                              \
    "paddq xmm3, xmm9;\n"                                                                                              \
    "paddq xmm3, xmm10;\n"                                                                                             \
    "paddq xmm3, xmm11;\n"                                                                                             \
    "paddq xmm3, xmm12;\n"                                                                                             \
    "paddq xmm3, xmm13;\n"                                                                                             \
    "paddq xmm3, xmm14;\n"                                                                                             \
    "paddq xmm3, xmm15;\n"                                                                                             \
    ";\n"                                                                                                              \
    "paddq xmm4, xmm0;\n"                                                                                              \
    "paddq xmm4, xmm1;\n"                                                                                              \
    "paddq xmm4, xmm2;\n"                                                                                              \
    "paddq xmm4, xmm3;\n"                                                                                              \
    "paddq xmm4, xmm4;\n"                                                                                              \
    "paddq xmm4, xmm5;\n"                                                                                              \
    "paddq xmm4, xmm6;\n"                                                                                              \
    "paddq xmm4, xmm7;\n"                                                                                              \
    "paddq xmm4, xmm8;\n"                                                                                              \
    "paddq xmm4, xmm9;\n"                                                                                              \
    "paddq xmm4, xmm10;\n"                                                                                             \
    "paddq xmm4, xmm11;\n"                                                                                             \
    "paddq xmm4, xmm12;\n"                                                                                             \
    "paddq xmm4, xmm13;\n"                                                                                             \
    "paddq xmm4, xmm14;\n"                                                                                             \
    "paddq xmm4, xmm15;\n"                                                                                             \
    ";\n"                                                                                                              \
    "paddq xmm5, xmm0;\n"                                                                                              \
    "paddq xmm5, xmm1;\n"                                                                                              \
    "paddq xmm5, xmm2;\n"                                                                                              \
    "paddq xmm5, xmm3;\n"                                                                                              \
    "paddq xmm5, xmm4;\n"                                                                                              \
    "paddq xmm5, xmm5;\n"                                                                                              \
    "paddq xmm5, xmm6;\n"                                                                                              \
    "paddq xmm5, xmm7;\n"                                                                                              \
    "paddq xmm5, xmm8;\n"                                                                                              \
    "paddq xmm5, xmm9;\n"                                                                                              \
    "paddq xmm5, xmm10;\n"                                                                                             \
    "paddq xmm5, xmm11;\n"                                                                                             \
    "paddq xmm5, xmm12;\n"                                                                                             \
    "paddq xmm5, xmm13;\n"                                                                                             \
    "paddq xmm5, xmm14;\n"                                                                                             \
    "paddq xmm5, xmm15;\n"                                                                                             \
    ";\n"                                                                                                              \
    "paddq xmm5, [rax+0xee];\n"                                                                                        \
    "paddq xmm5, [rcx+0xdd];\n"                                                                                        \
    "paddq xmm5, [rdx+0x8efde];\n"                                                                                     \
    "paddq xmm5, [rbx+0x4cd];\n"                                                                                       \
    "paddq xmm5, [rsp+0xaa];\n"                                                                                        \
    "paddq xmm5, [rbp+0xff];\n"                                                                                        \
    "paddq xmm5, [rsi+0xfddd];\n"                                                                                      \
    "paddq xmm5, [rdi+0xabcd];\n"                                                                                      \
    "paddq xmm5, [r8+0x9a9a9];\n"                                                                                      \
    "paddq xmm5, [r9+0x456];\n"                                                                                        \
    "paddq xmm5, [r10+0x123];\n"                                                                                       \
    "paddq xmm5, [r11+0x89dd];\n"                                                                                      \
    "paddq xmm5, [r12+0x9a34];\n"                                                                                      \
    "paddq xmm5, [r13+0xffff];\n"                                                                                      \
    "paddq xmm5, [r14+0x4edf];\n"                                                                                      \
    "paddq xmm5, [r15+0xfe];\n"                                                                                        \
    ";\n"                                                                                                              \
    "paddq xmm6, xmm0;\n"                                                                                              \
    "paddq xmm6, xmm1;\n"                                                                                              \
    "paddq xmm6, xmm2;\n"                                                                                              \
    "paddq xmm6, xmm3;\n"                                                                                              \
    "paddq xmm6, xmm4;\n"                                                                                              \
    "paddq xmm6, xmm5;\n"                                                                                              \
    "paddq xmm6, xmm6;\n"                                                                                              \
    "paddq xmm6, xmm7;\n"                                                                                              \
    "paddq xmm6, xmm8;\n"                                                                                              \
    "paddq xmm6, xmm9;\n"                                                                                              \
    "paddq xmm6, xmm10;\n"                                                                                             \
    "paddq xmm6, xmm11;\n"                                                                                             \
    "paddq xmm6, xmm12;\n"                                                                                             \
    "paddq xmm6, xmm13;\n"                                                                                             \
    "paddq xmm6, xmm14;\n"                                                                                             \
    "paddq xmm6, xmm15;\n"                                                                                             \
    ";\n"                                                                                                              \
    "paddq xmm7, xmm0;\n"                                                                                              \
    "paddq xmm7, xmm1;\n"                                                                                              \
    "paddq xmm7, xmm2;\n"                                                                                              \
    "paddq xmm7, xmm3;\n"                                                                                              \
    "paddq xmm7, xmm4;\n"                                                                                              \
    "paddq xmm7, xmm5;\n"                                                                                              \
    "paddq xmm7, xmm6;\n"                                                                                              \
    "paddq xmm7, xmm7;\n"                                                                                              \
    "paddq xmm7, xmm8;\n"                                                                                              \
    "paddq xmm7, xmm9;\n"                                                                                              \
    "paddq xmm7, xmm10;\n"                                                                                             \
    "paddq xmm7, xmm11;\n"                                                                                             \
    "paddq xmm7, xmm12;\n"                                                                                             \
    "paddq xmm7, xmm13;\n"                                                                                             \
    "paddq xmm7, xmm14;\n"                                                                                             \
    "paddq xmm7, xmm15;\n"                                                                                             \
    ";\n"                                                                                                              \
    "paddq xmm8, xmm0;\n"                                                                                              \
    "paddq xmm8, xmm1;\n"                                                                                              \
    "paddq xmm8, xmm2;\n"                                                                                              \
    "paddq xmm8, xmm3;\n"                                                                                              \
    "paddq xmm8, xmm4;\n"                                                                                              \
    "paddq xmm8, xmm5;\n"                                                                                              \
    "paddq xmm8, xmm6;\n"                                                                                              \
    "paddq xmm8, xmm7;\n"                                                                                              \
    "paddq xmm8, xmm8;\n"                                                                                              \
    "paddq xmm8, xmm9;\n"                                                                                              \
    "paddq xmm8, xmm10;\n"                                                                                             \
    "paddq xmm8, xmm11;\n"                                                                                             \
    "paddq xmm8, xmm12;\n"                                                                                             \
    "paddq xmm8, xmm13;\n"                                                                                             \
    "paddq xmm8, xmm14;\n"                                                                                             \
    "paddq xmm8, xmm15;\n"                                                                                             \
    ";\n"                                                                                                              \
    "paddq xmm9, xmm0;\n"                                                                                              \
    "paddq xmm9, xmm1;\n"                                                                                              \
    "paddq xmm9, xmm2;\n"                                                                                              \
    "paddq xmm9, xmm3;\n"                                                                                              \
    "paddq xmm9, xmm4;\n"                                                                                              \
    "paddq xmm9, xmm5;\n"                                                                                              \
    "paddq xmm9, xmm6;\n"                                                                                              \
    "paddq xmm9, xmm7;\n"                                                                                              \
    "paddq xmm9, xmm8;\n"                                                                                              \
    "paddq xmm9, xmm9;\n"                                                                                              \
    "paddq xmm9, xmm10;\n"                                                                                             \
    "paddq xmm9, xmm11;\n"                                                                                             \
    "paddq xmm9, xmm12;\n"                                                                                             \
    "paddq xmm9, xmm13;\n"                                                                                             \
    "paddq xmm9, xmm14;\n"                                                                                             \
    "paddq xmm9, xmm15;\n"                                                                                             \
    ";\n"                                                                                                              \
    "paddq xmm10, xmm0;\n"                                                                                             \
    "paddq xmm10, xmm1;\n"                                                                                             \
    "paddq xmm10, xmm2;\n"                                                                                             \
    "paddq xmm10, xmm3;\n"                                                                                             \
    "paddq xmm10, xmm4;\n"                                                                                             \
    "paddq xmm10, xmm5;\n"                                                                                             \
    "paddq xmm10, xmm6;\n"                                                                                             \
    "paddq xmm10, xmm7;\n"                                                                                             \
    "paddq xmm10, xmm8;\n"                                                                                             \
    "paddq xmm10, xmm9;\n"                                                                                             \
    "paddq xmm10, xmm10;\n"                                                                                            \
    "paddq xmm10, xmm11;\n"                                                                                            \
    "paddq xmm10, xmm12;\n"                                                                                            \
    "paddq xmm10, xmm13;\n"                                                                                            \
    "paddq xmm10, xmm14;\n"                                                                                            \
    "paddq xmm10, xmm15;\n"                                                                                            \
    ";\n"                                                                                                              \
    "paddq xmm11, xmm0;\n"                                                                                             \
    "paddq xmm11, xmm1;\n"                                                                                             \
    "paddq xmm11, xmm2;\n"                                                                                             \
    "paddq xmm11, xmm3;\n"                                                                                             \
    "paddq xmm11, xmm4;\n"                                                                                             \
    "paddq xmm11, xmm5;\n"                                                                                             \
    "paddq xmm11, xmm6;\n"                                                                                             \
    "paddq xmm11, xmm7;\n"                                                                                             \
    "paddq xmm11, xmm8;\n"                                                                                             \
    "paddq xmm11, xmm9;\n"                                                                                             \
    "paddq xmm11, xmm10;\n"                                                                                            \
    "paddq xmm11, xmm11;\n"                                                                                            \
    "paddq xmm11, xmm12;\n"                                                                                            \
    "paddq xmm11, xmm13;\n"                                                                                            \
    "paddq xmm11, xmm14;\n"                                                                                            \
    "paddq xmm11, xmm15;\n"                                                                                            \
    ";\n"                                                                                                              \
    "paddq xmm11, [rax+0xee];\n"                                                                                       \
    "paddq xmm11, [rcx+0xdd];\n"                                                                                       \
    "paddq xmm11, [rdx+0x8efde];\n"                                                                                    \
    "paddq xmm11, [rbx+0x4cd];\n"                                                                                      \
    "paddq xmm11, [rsp+0xaa];\n"                                                                                       \
    "paddq xmm11, [rbp+0xff];\n"                                                                                       \
    "paddq xmm11, [rsi+0xfddd];\n"                                                                                     \
    "paddq xmm11, [rdi+0xabcd];\n"                                                                                     \
    "paddq xmm11, [r8+0x9a9a9];\n"                                                                                     \
    "paddq xmm11, [r9+0x456];\n"                                                                                       \
    "paddq xmm11, [r10+0x123];\n"                                                                                      \
    "paddq xmm11, [r11+0x89dd];\n"                                                                                     \
    "paddq xmm11, [r12+0x9a34];\n"                                                                                     \
    "paddq xmm11, [r13+0xffff];\n"                                                                                     \
    "paddq xmm11, [r14+0x4edf];\n"                                                                                     \
    "paddq xmm11, [r15+0xfe];\n"                                                                                       \
    ";\n"                                                                                                              \
    "paddq xmm12, xmm0;\n"                                                                                             \
    "paddq xmm12, xmm1;\n"                                                                                             \
    "paddq xmm12, xmm2;\n"                                                                                             \
    "paddq xmm12, xmm3;\n"                                                                                             \
    "paddq xmm12, xmm4;\n"                                                                                             \
    "paddq xmm12, xmm5;\n"                                                                                             \
    "paddq xmm12, xmm6;\n"                                                                                             \
    "paddq xmm12, xmm7;\n"                                                                                             \
    "paddq xmm12, xmm8;\n"                                                                                             \
    "paddq xmm12, xmm9;\n"                                                                                             \
    "paddq xmm12, xmm10;\n"                                                                                            \
    "paddq xmm12, xmm11;\n"                                                                                            \
    "paddq xmm12, xmm12;\n"                                                                                            \
    "paddq xmm12, xmm13;\n"                                                                                            \
    "paddq xmm12, xmm14;\n"                                                                                            \
    "paddq xmm12, xmm15;\n"                                                                                            \
    ";\n"                                                                                                              \
    "paddq xmm13, xmm0;\n"                                                                                             \
    "paddq xmm13, xmm1;\n"                                                                                             \
    "paddq xmm13, xmm2;\n"                                                                                             \
    "paddq xmm13, xmm3;\n"                                                                                             \
    "paddq xmm13, xmm4;\n"                                                                                             \
    "paddq xmm13, xmm5;\n"                                                                                             \
    "paddq xmm13, xmm6;\n"                                                                                             \
    "paddq xmm13, xmm7;\n"                                                                                             \
    "paddq xmm13, xmm8;\n"                                                                                             \
    "paddq xmm13, xmm9;\n"                                                                                             \
    "paddq xmm13, xmm10;\n"                                                                                            \
    "paddq xmm13, xmm11;\n"                                                                                            \
    "paddq xmm13, xmm12;\n"                                                                                            \
    "paddq xmm13, xmm13;\n"                                                                                            \
    "paddq xmm13, xmm14;\n"                                                                                            \
    "paddq xmm13, xmm15;\n"                                                                                            \
    ";\n"                                                                                                              \
    "paddq xmm14, xmm0;\n"                                                                                             \
    "paddq xmm14, xmm1;\n"                                                                                             \
    "paddq xmm14, xmm2;\n"                                                                                             \
    "paddq xmm14, xmm3;\n"                                                                                             \
    "paddq xmm14, xmm4;\n"                                                                                             \
    "paddq xmm14, xmm5;\n"                                                                                             \
    "paddq xmm14, xmm6;\n"                                                                                             \
    "paddq xmm14, xmm7;\n"                                                                                             \
    "paddq xmm14, xmm8;\n"                                                                                             \
    "paddq xmm14, xmm9;\n"                                                                                             \
    "paddq xmm14, xmm10;\n"                                                                                            \
    "paddq xmm14, xmm11;\n"                                                                                            \
    "paddq xmm14, xmm12;\n"                                                                                            \
    "paddq xmm14, xmm13;\n"                                                                                            \
    "paddq xmm14, xmm14;\n"                                                                                            \
    "paddq xmm14, xmm15;\n"                                                                                            \
    ";\n"                                                                                                              \
    "paddq xmm0, xmm0;\n"                                                                                              \
    "paddq xmm0, xmm1;\n"                                                                                              \
    "paddq xmm0, xmm2;\n"                                                                                              \
    "paddq xmm0, xmm3;\n"                                                                                              \
    "paddq xmm0, xmm4;\n"                                                                                              \
    "paddq xmm0, xmm5;\n"                                                                                              \
    "paddq xmm0, xmm6;\n"                                                                                              \
    "paddq xmm0, xmm7;\n"                                                                                              \
    "paddq xmm0, xmm8;\n"                                                                                              \
    "paddq xmm0, xmm9;\n"                                                                                              \
    "paddq xmm0, xmm10;\n"                                                                                             \
    "paddq xmm0, xmm11;\n"                                                                                             \
    "paddq xmm0, xmm12;\n"                                                                                             \
    "paddq xmm0, xmm13;\n"                                                                                             \
    "paddq xmm0, xmm14;\n"                                                                                             \
    "paddq xmm0, xmm15;\n" 
