#define CODE                                                                                                           \
    "prefetcht0 [rbp];\n"                                                                                              \
    "prefetcht0 [rsi];\n"                                                                                              \
    "prefetcht0 [rdi];\n"                                                                                              \
    "prefetcht0 [rsp];\n"                                                                                              \
    "prefetcht0 [rbp];\n"                                                                                              \
    "prefetcht0 [r9];\n"                                                                                               \
    "prefetcht0 [r10];\n"                                                                                              \
    "prefetcht0 [r11];\n"                                                                                              \
    "prefetcht0 [r12];\n"                                                                                              \
    "prefetcht0 [r13];\n"                                                                                              \
    "prefetcht0 [r14];\n"                                                                                              \
    "prefetcht0 [r15];\n"                                                                                              \
    "prefetcht1 [rdi];\n"                                                                                              \
    "prefetcht1 [rbp];\n"                                                                                              \
    "prefetcht1 [rsi];\n"                                                                                              \
    "prefetcht1 [rdi];\n"                                                                                              \
    "prefetcht1 [rsp];\n"                                                                                              \
    "prefetcht1 [rbp];\n"                                                                                              \
    "prefetcht1 [r9];\n"                                                                                               \
    "prefetcht1 [r10];\n"                                                                                              \
    "prefetcht1 [r11];\n"                                                                                              \
    "prefetcht1 [r12];\n"                                                                                              \
    "prefetcht1 [r13];\n"                                                                                              \
    "prefetcht1 [r14];\n"                                                                                              \
    "prefetcht1 [r15];\n"                                                                                              \
    "prefetcht2 [rbp];\n"                                                                                              \
    "prefetcht2 [rsi];\n"                                                                                              \
    "prefetcht2 [rdi];\n"                                                                                              \
    "prefetcht2 [rsp];\n"                                                                                              \
    "prefetcht2 [rbp];\n"                                                                                              \
    "prefetcht2 [r9];\n"                                                                                               \
    "prefetcht2 [r10];\n"                                                                                              \
    "prefetcht2 [r11];\n"                                                                                              \
    "prefetcht2 [r12];\n"                                                                                              \
    "prefetcht2 [r13];\n"                                                                                              \
    "prefetcht2 [r14];\n"                                                                                              \
    "prefetcht2 [r15];\n"                                                                                              \
    "prefetchnta [rbp];\n"                                                                                             \
    "prefetchnta [rsi];\n"                                                                                             \
    "prefetchnta [rdi];\n"                                                                                             \
    "prefetchnta [rsp];\n"                                                                                             \
    "prefetchnta [rbp];\n"                                                                                             \
    "prefetchnta [r9];\n"                                                                                              \
    "prefetchnta [r10];\n"                                                                                             \
    "prefetchnta [r11];\n"                                                                                             \
    "prefetchnta [r12];\n"                                                                                             \
    "prefetchnta [r13];\n"                                                                                             \
    "prefetchnta [r14];\n"                                                                                             \
    "prefetchnta [r15];\n"                                                                                             \
    ""
