#define CODE                                                                                                           \
    "sub al, 0x0;\n"                                                                                                   \
    "sub ax, 0xe1;\n"                                                                                                  \
    "sub eax, 0xe11;\n"                                                                                                \
    "sub ax, 0xe2;\n"                                                                                                  \
    "sub eax, 0xeff;\n"                                                                                                \
    "sub ax, 0xe0;\n"                                                                                                  \
    "sub sil, 0x0;\n"                                                                                                  \
    "sub si, 0xe1;\n"                                                                                                  \
    "sub esi, 0xe11;\n"                                                                                                \
    "sub rax, 0xfffee12;\n"                                                                                            \
    "sub rax, 0xff6ee12;\n"                                                                                            \
    "sub rax, 0xf66ee12;\n"                                                                                            \
    "sub rax, 0x666ee12;\n"                                                                                            \
    "sub rax, 0x6666ee12;\n"                                                                                           \
    "sub rax, -0x1;\n"                                                                                                 \
    "sub rax, -0xfffee12;\n"                                                                                           \
    "sub rax, -0xff6ee12;\n"                                                                                           \
    "sub rax, -0xf66ee12;\n"                                                                                           \
    "sub rax, -0x666ee12;\n"                                                                                           \
    "sub rax, -0x6666ee12;\n"                                                                                          \
    "sub rbp, -0xfffee12;\n"                                                                                           \
    "sub rbp, 0xfffee12;\n"                                                                                            \
    "sub rbp, 0xff6ee12;\n"                                                                                            \
    "sub rbp, 0xf66ee12;\n"                                                                                            \
    "sub rbp, 0x666ee12;\n"                                                                                            \
    "sub rbp, 0x6666ee12;\n"                                                                                           \
    "sub rbp, -0xf;\n"                                                                                                 \
    "sub rbp, -0xe;\n"                                                                                                 \
    "sub rbp, -0xd;\n"                                                                                                 \
    "sub rbp, -0x7;\n"                                                                                                 \
    "sub rbp, -0x4;\n"                                                                                                 \
    "sub rbp, -0x3;\n"                                                                                                 \
    "sub rbp, -0x2;\n"                                                                                                 \
    "sub rbp, -0xff;\n"                                                                                                \
    "sub rbp, -0xef;\n"                                                                                                \
    "sub rbp, -0xdf;\n"                                                                                                \
    "sub rbp, -0xcf;\n"                                                                                                \
    "sub rbp, -0xbf;\n"                                                                                                \
    "sub rbp, -0xaf;\n"                                                                                                \
    "sub rbp, -0x9f;\n"                                                                                                \
    "sub rbp, -0x8f;\n"                                                                                                \
    "sub rbp, -0x7f;\n"                                                                                                \
    "sub rbp, -0x3e;\n"                                                                                                \
    "sub rbp, -0x6f;\n"                                                                                                \
    "sub rbp, -0x5f;\n"                                                                                                \
    "sub rbp, -0x4f;\n"                                                                                                \
    "sub rbp, -0x1f;\n"                                                                                                \
    "sub rbp, -0xfa;\n"                                                                                                \
    "sub rbp, -0xf9;\n"                                                                                                \
    "sub rbp, -0xf8;\n"                                                                                                \
    "sub rbp, -0xf7;\n"                                                                                                \
    "sub rbp, -0xf6;\n"                                                                                                \
    "sub rbp, -0xf5;\n"                                                                                                \
    "sub rbp, -0xf4;\n"                                                                                                \
    "sub rbp, -0xf3;\n"                                                                                                \
    "sub rbp, -0xf2;\n"                                                                                                \
    "sub rbp, -0xf1;\n"                                                                                                \
    "sub rbp, -0xf66;\n"                                                                                               \
    "sub rbp, -0x666ee;\n"                                                                                             \
    "sub rbp, -0x6666ee12;\n"                                                                                          \
    "sub r13, -0xfffee12;\n"                                                                                           \
    "sub r13, 0xfffee12;\n"                                                                                            \
    "sub r13, 0xff6ee12;\n"                                                                                            \
    "sub r13, 0xf66ee12;\n"                                                                                            \
    "sub r13, 0x666ee12;\n"                                                                                            \
    "sub r13, 0x6666ee12;\n"                                                                                           \
    "sub r13, -0x1;\n"                                                                                                 \
    "sub r13, -0xfffee12;\n"                                                                                           \
    "sub r13, -0xff6ee12;\n"                                                                                           \
    "sub r13, -0xf66ee12;\n"                                                                                           \
    "sub r13, -0x666ee12;\n"                                                                                           \
    "sub r13, -0x6666ee12;\n"                                                                                          \
    "sub rax, 0x12;\n"                                                                                                 \
    "sub rax, 0xe12;\n"                                                                                                \
    "sub rax, 0x66ee12;\n"                                                                                             \
    "sub rax, 0x66ee12;\n"                                                                                             \
    "sub rax, 0x6ee12;\n"                                                                                              \
    "sub r11, r10;\n"                                                                                                  \
    "sub rsp, 0x138 ;\n"                                                                                               \
    "sub rsp, 0x48 ;\n"                                                                                                \
    "sub rsp, 0x50 ;\n"                                                                                                \
    "sub rsp, 0x80 ;\n"                                                                                                \
    ""
