#define CODE                                                                                                           \
    "sbb al, 0x0;\n"                                                                                                   \
    "sbb ax, 0xe1;\n"                                                                                                  \
    "sbb eax, 0xe11;\n"                                                                                                \
    "sbb sil, 0x0;\n"                                                                                                  \
    "sbb si, 0xe1;\n"                                                                                                  \
    "sbb esi, 0xe11;\n"                                                                                                \
    "sbb rax, 0xfffee12;\n"                                                                                            \
    "sbb rax, 0xff6ee12;\n"                                                                                            \
    "sbb rax, 0xf66ee12;\n"                                                                                            \
    "sbb rax, 0x666ee12;\n"                                                                                            \
    "sbb rax, 0x6666ee12;\n"                                                                                           \
    "sbb rax, -0x1;\n"                                                                                                 \
    "sbb rax, -0xfffee12;\n"                                                                                           \
    "sbb rax, -0xff6ee12;\n"                                                                                           \
    "sbb rax, -0xf66ee12;\n"                                                                                           \
    "sbb rax, -0x666ee12;\n"                                                                                           \
    "sbb rax, -0x6666ee12;\n"                                                                                          \
    "sbb rbp, -0xfffee12;\n"                                                                                           \
    "sbb rbp, 0xfffee12;\n"                                                                                            \
    "sbb rbp, 0xff6ee12;\n"                                                                                            \
    "sbb rbp, 0xf66ee12;\n"                                                                                            \
    "sbb rbp, 0x666ee12;\n"                                                                                            \
    "sbb rbp, 0x6666ee12;\n"                                                                                           \
    "sbb rbp, -0xf;\n"                                                                                                 \
    "sbb rbp, -0xe;\n"                                                                                                 \
    "sbb rbp, -0xd;\n"                                                                                                 \
    "sbb rbp, -0x7;\n"                                                                                                 \
    "sbb rbp, -0x4;\n"                                                                                                 \
    "sbb rbp, -0x3;\n"                                                                                                 \
    "sbb rbp, -0x2;\n"                                                                                                 \
    "sbb rbp, -0xff;\n"                                                                                                \
    "sbb rbp, -0xef;\n"                                                                                                \
    "sbb rbp, -0xdf;\n"                                                                                                \
    "sbb rbp, -0xcf;\n"                                                                                                \
    "sbb rbp, -0xbf;\n"                                                                                                \
    "sbb rbp, -0xaf;\n"                                                                                                \
    "sbb rbp, -0x9f;\n"                                                                                                \
    "sbb rbp, -0x8f;\n"                                                                                                \
    "sbb rbp, -0x7f;\n"                                                                                                \
    "sbb rbp, -0x3e;\n"                                                                                                \
    "sbb rbp, -0x6f;\n"                                                                                                \
    "sbb rbp, -0x5f;\n"                                                                                                \
    "sbb rbp, -0x4f;\n"                                                                                                \
    "sbb rbp, -0x1f;\n"                                                                                                \
    "sbb rbp, -0xfa;\n"                                                                                                \
    "sbb rbp, -0xf9;\n"                                                                                                \
    "sbb rbp, -0xf8;\n"                                                                                                \
    "sbb rbp, -0xf7;\n"                                                                                                \
    "sbb rbp, -0xf6;\n"                                                                                                \
    "sbb rbp, -0xf5;\n"                                                                                                \
    "sbb rbp, -0xf4;\n"                                                                                                \
    "sbb rbp, -0xf3;\n"                                                                                                \
    "sbb rbp, -0xf2;\n"                                                                                                \
    "sbb rbp, -0xf1;\n"                                                                                                \
    "sbb rbp, -0xf66;\n"                                                                                               \
    "sbb rbp, -0x666ee;\n"                                                                                             \
    "sbb rbp, -0x6666ee12;\n"                                                                                          \
    "sbb r13, -0xfffee12;\n"                                                                                           \
    "sbb r13, 0xfffee12;\n"                                                                                            \
    "sbb r13, 0xff6ee12;\n"                                                                                            \
    "sbb r13, 0xf66ee12;\n"                                                                                            \
    "sbb r13, 0x666ee12;\n"                                                                                            \
    "sbb r13, 0x6666ee12;\n"                                                                                           \
    "sbb r13, -0x1;\n"                                                                                                 \
    "sbb r13, -0xfffee12;\n"                                                                                           \
    "sbb r13, -0xff6ee12;\n"                                                                                           \
    "sbb r13, -0xf66ee12;\n"                                                                                           \
    "sbb r13, -0x666ee12;\n"                                                                                           \
    "sbb r13, -0x6666ee12;\n"                                                                                          \
    "sbb rax, 0x12;\n"                                                                                                 \
    "sbb rax, 0xe12;\n"                                                                                                \
    "sbb rax, 0x66ee12;\n"                                                                                             \
    "sbb rax, 0x66ee12;\n"                                                                                             \
    "sbb rax, 0x6ee12;\n"                                                                                              \
    "sbb sp, 0x34ef;\n"                                                                                                \
    "sbb r8w, 0x1;\n"                                                                                                  \
    "sbb rax, [ rbx ];\n"                                                                                              \
    "sbb rax, [ rbx + 0x10 ];\n"                                                                                       \
    "sbb rax, 0x0 ;\n"                                                                                                 \
    "sbb rax, 0x0;\n"                                                                                                  \
    "sbb r12, r14;\n"                                                                                                  \
    "sbb r12, rbx;\n"                                                                                                  \
    "sbb r12, [ rsp + 0x10 ];\n"                                                                                       \
    "sbb rax, 0xfff;\n"                                                                                                \
    "sbb rax, r15;\n"                                                                                                  \
    "sbb rax, rbp;\n"                                                                                                  \
    "sbb rbp, r12;\n"                                                                                                  \
    "sbb rbp, r8;\n"                                                                                                   \
    "sbb rbp, r9;\n"                                                                                                   \
    "sbb rbx, r9;\n"                                                                                                   \
    "sbb rbx, rdi;\n"                                                                                                  \
    "sbb rdi, r10;\n"                                                                                                  \
    "sbb rdx, r14;\n"                                                                                                  \
    "sbb rsp, 0x138 ;\n"                                                                                               \
    "sbb rsp, 0x48 ;\n"                                                                                                \
    "sbb rsp, 0x50 ;\n"                                                                                                \
    "sbb rsp, 0x80 ;\n"
