#define CODE                                                                                                           \
    "pmuludq xmm0, xmm0;\n"                                                                                            \
    "pmuludq xmm0, xmm1;\n"                                                                                            \
    "pmuludq xmm0, xmm2;\n"                                                                                            \
    "pmuludq xmm0, xmm3;\n"                                                                                            \
    "pmuludq xmm0, xmm4;\n"                                                                                            \
    "pmuludq xmm0, xmm5;\n"                                                                                            \
    "pmuludq xmm0, xmm6;\n"                                                                                            \
    "pmuludq xmm0, xmm7;\n"                                                                                            \
    "pmuludq xmm0, xmm8;\n"                                                                                            \
    "pmuludq xmm0, xmm9;\n"                                                                                            \
    "pmuludq xmm0, xmm10;\n"                                                                                           \
    "pmuludq xmm0, xmm11;\n"                                                                                           \
    "pmuludq xmm0, xmm12;\n"                                                                                           \
    "pmuludq xmm0, xmm13;\n"                                                                                           \
    "pmuludq xmm0, xmm14;\n"                                                                                           \
    "pmuludq xmm0, xmm15;\n"                                                                                           \
    ";\n"                                                                                                              \
    "pmuludq xmm1, xmm0;\n"                                                                                            \
    "pmuludq xmm1, xmm1;\n"                                                                                            \
    "pmuludq xmm1, xmm2;\n"                                                                                            \
    "pmuludq xmm1, xmm3;\n"                                                                                            \
    "pmuludq xmm1, xmm4;\n"                                                                                            \
    "pmuludq xmm1, xmm5;\n"                                                                                            \
    "pmuludq xmm1, xmm6;\n"                                                                                            \
    "pmuludq xmm1, xmm7;\n"                                                                                            \
    "pmuludq xmm1, xmm8;\n"                                                                                            \
    "pmuludq xmm1, xmm9;\n"                                                                                            \
    "pmuludq xmm1, xmm10;\n"                                                                                           \
    "pmuludq xmm1, xmm11;\n"                                                                                           \
    "pmuludq xmm1, xmm12;\n"                                                                                           \
    "pmuludq xmm1, xmm13;\n"                                                                                           \
    "pmuludq xmm1, xmm14;\n"                                                                                           \
    "pmuludq xmm1, xmm15;\n"                                                                                           \
    ";\n"                                                                                                              \
    "pmuludq xmm2, xmm0;\n"                                                                                            \
    "pmuludq xmm2, xmm1;\n"                                                                                            \
    "pmuludq xmm2, xmm2;\n"                                                                                            \
    "pmuludq xmm2, xmm3;\n"                                                                                            \
    "pmuludq xmm2, xmm4;\n"                                                                                            \
    "pmuludq xmm2, xmm5;\n"                                                                                            \
    "pmuludq xmm2, xmm6;\n"                                                                                            \
    "pmuludq xmm2, xmm7;\n"                                                                                            \
    "pmuludq xmm2, xmm8;\n"                                                                                            \
    "pmuludq xmm2, xmm9;\n"                                                                                            \
    "pmuludq xmm2, xmm10;\n"                                                                                           \
    "pmuludq xmm2, xmm11;\n"                                                                                           \
    "pmuludq xmm2, xmm12;\n"                                                                                           \
    "pmuludq xmm2, xmm13;\n"                                                                                           \
    "pmuludq xmm2, xmm14;\n"                                                                                           \
    "pmuludq xmm2, xmm15;\n"                                                                                           \
    ";\n"                                                                                                              \
    "pmuludq xmm3, xmm0;\n"                                                                                            \
    "pmuludq xmm3, xmm1;\n"                                                                                            \
    "pmuludq xmm3, xmm2;\n"                                                                                            \
    "pmuludq xmm3, xmm3;\n"                                                                                            \
    "pmuludq xmm3, xmm4;\n"                                                                                            \
    "pmuludq xmm3, xmm5;\n"                                                                                            \
    "pmuludq xmm3, xmm6;\n"                                                                                            \
    "pmuludq xmm3, xmm7;\n"                                                                                            \
    "pmuludq xmm3, xmm8;\n"                                                                                            \
    "pmuludq xmm3, xmm9;\n"                                                                                            \
    "pmuludq xmm3, xmm10;\n"                                                                                           \
    "pmuludq xmm3, xmm11;\n"                                                                                           \
    "pmuludq xmm3, xmm12;\n"                                                                                           \
    "pmuludq xmm3, xmm13;\n"                                                                                           \
    "pmuludq xmm3, xmm14;\n"                                                                                           \
    "pmuludq xmm3, xmm15;\n"                                                                                           \
    ";\n"                                                                                                              \
    "pmuludq xmm4, xmm0;\n"                                                                                            \
    "pmuludq xmm4, xmm1;\n"                                                                                            \
    "pmuludq xmm4, xmm2;\n"                                                                                            \
    "pmuludq xmm4, xmm3;\n"                                                                                            \
    "pmuludq xmm4, xmm4;\n"                                                                                            \
    "pmuludq xmm4, xmm5;\n"                                                                                            \
    "pmuludq xmm4, xmm6;\n"                                                                                            \
    "pmuludq xmm4, xmm7;\n"                                                                                            \
    "pmuludq xmm4, xmm8;\n"                                                                                            \
    "pmuludq xmm4, xmm9;\n"                                                                                            \
    "pmuludq xmm4, xmm10;\n"                                                                                           \
    "pmuludq xmm4, xmm11;\n"                                                                                           \
    "pmuludq xmm4, xmm12;\n"                                                                                           \
    "pmuludq xmm4, xmm13;\n"                                                                                           \
    "pmuludq xmm4, xmm14;\n"                                                                                           \
    "pmuludq xmm4, xmm15;\n"                                                                                           \
    ";\n"                                                                                                              \
    "pmuludq xmm5, xmm0;\n"                                                                                            \
    "pmuludq xmm5, xmm1;\n"                                                                                            \
    "pmuludq xmm5, xmm2;\n"                                                                                            \
    "pmuludq xmm5, xmm3;\n"                                                                                            \
    "pmuludq xmm5, xmm4;\n"                                                                                            \
    "pmuludq xmm5, xmm5;\n"                                                                                            \
    "pmuludq xmm5, xmm6;\n"                                                                                            \
    "pmuludq xmm5, xmm7;\n"                                                                                            \
    "pmuludq xmm5, xmm8;\n"                                                                                            \
    "pmuludq xmm5, xmm9;\n"                                                                                            \
    "pmuludq xmm5, xmm10;\n"                                                                                           \
    "pmuludq xmm5, xmm11;\n"                                                                                           \
    "pmuludq xmm5, xmm12;\n"                                                                                           \
    "pmuludq xmm5, xmm13;\n"                                                                                           \
    "pmuludq xmm5, xmm14;\n"                                                                                           \
    "pmuludq xmm5, xmm15;\n"                                                                                           \
    ";\n"                                                                                                              \
    "pmuludq xmm6, xmm0;\n"                                                                                            \
    "pmuludq xmm6, xmm1;\n"                                                                                            \
    "pmuludq xmm6, xmm2;\n"                                                                                            \
    "pmuludq xmm6, xmm3;\n"                                                                                            \
    "pmuludq xmm6, xmm4;\n"                                                                                            \
    "pmuludq xmm6, xmm5;\n"                                                                                            \
    "pmuludq xmm6, xmm6;\n"                                                                                            \
    "pmuludq xmm6, xmm7;\n"                                                                                            \
    "pmuludq xmm6, xmm8;\n"                                                                                            \
    "pmuludq xmm6, xmm9;\n"                                                                                            \
    "pmuludq xmm6, xmm10;\n"                                                                                           \
    "pmuludq xmm6, xmm11;\n"                                                                                           \
    "pmuludq xmm6, xmm12;\n"                                                                                           \
    "pmuludq xmm6, xmm13;\n"                                                                                           \
    "pmuludq xmm6, xmm14;\n"                                                                                           \
    "pmuludq xmm6, xmm15;\n"                                                                                           \
    ";\n"                                                                                                              \
    "pmuludq xmm7, xmm0;\n"                                                                                            \
    "pmuludq xmm7, xmm1;\n"                                                                                            \
    "pmuludq xmm7, xmm2;\n"                                                                                            \
    "pmuludq xmm7, xmm3;\n"                                                                                            \
    "pmuludq xmm7, xmm4;\n"                                                                                            \
    "pmuludq xmm7, xmm5;\n"                                                                                            \
    "pmuludq xmm7, xmm6;\n"                                                                                            \
    "pmuludq xmm7, xmm7;\n"                                                                                            \
    "pmuludq xmm7, xmm8;\n"                                                                                            \
    "pmuludq xmm7, xmm9;\n"                                                                                            \
    "pmuludq xmm7, xmm10;\n"                                                                                           \
    "pmuludq xmm7, xmm11;\n"                                                                                           \
    "pmuludq xmm7, xmm12;\n"                                                                                           \
    "pmuludq xmm7, xmm13;\n"                                                                                           \
    "pmuludq xmm7, xmm14;\n"                                                                                           \
    "pmuludq xmm7, xmm15;\n"                                                                                           \
    ";\n"                                                                                                              \
    "pmuludq xmm8, xmm0;\n"                                                                                            \
    "pmuludq xmm8, xmm1;\n"                                                                                            \
    "pmuludq xmm8, xmm2;\n"                                                                                            \
    "pmuludq xmm8, xmm3;\n"                                                                                            \
    "pmuludq xmm8, xmm4;\n"                                                                                            \
    "pmuludq xmm8, xmm5;\n"                                                                                            \
    "pmuludq xmm8, xmm6;\n"                                                                                            \
    "pmuludq xmm8, xmm7;\n"                                                                                            \
    "pmuludq xmm8, xmm8;\n"                                                                                            \
    "pmuludq xmm8, xmm9;\n"                                                                                            \
    "pmuludq xmm8, xmm10;\n"                                                                                           \
    "pmuludq xmm8, xmm11;\n"                                                                                           \
    "pmuludq xmm8, xmm12;\n"                                                                                           \
    "pmuludq xmm8, xmm13;\n"                                                                                           \
    "pmuludq xmm8, xmm14;\n"                                                                                           \
    "pmuludq xmm8, xmm15;\n"                                                                                           \
    ";\n"                                                                                                              \
    "pmuludq xmm9, xmm0;\n"                                                                                            \
    "pmuludq xmm9, xmm1;\n"                                                                                            \
    "pmuludq xmm9, xmm2;\n"                                                                                            \
    "pmuludq xmm9, xmm3;\n"                                                                                            \
    "pmuludq xmm9, xmm4;\n"                                                                                            \
    "pmuludq xmm9, xmm5;\n"                                                                                            \
    "pmuludq xmm9, xmm6;\n"                                                                                            \
    "pmuludq xmm9, xmm7;\n"                                                                                            \
    "pmuludq xmm9, xmm8;\n"                                                                                            \
    "pmuludq xmm9, xmm9;\n"                                                                                            \
    "pmuludq xmm9, xmm10;\n"                                                                                           \
    "pmuludq xmm9, xmm11;\n"                                                                                           \
    "pmuludq xmm9, xmm12;\n"                                                                                           \
    "pmuludq xmm9, xmm13;\n"                                                                                           \
    "pmuludq xmm9, xmm14;\n"                                                                                           \
    "pmuludq xmm9, xmm15;\n"                                                                                           \
    ";\n"                                                                                                              \
    "pmuludq xmm10, xmm0;\n"                                                                                           \
    "pmuludq xmm10, xmm1;\n"                                                                                           \
    "pmuludq xmm10, xmm2;\n"                                                                                           \
    "pmuludq xmm10, xmm3;\n"                                                                                           \
    "pmuludq xmm10, xmm4;\n"                                                                                           \
    "pmuludq xmm10, xmm5;\n"                                                                                           \
    "pmuludq xmm10, xmm6;\n"                                                                                           \
    "pmuludq xmm10, xmm7;\n"                                                                                           \
    "pmuludq xmm10, xmm8;\n"                                                                                           \
    "pmuludq xmm10, xmm9;\n"                                                                                           \
    "pmuludq xmm10, xmm10;\n"                                                                                          \
    "pmuludq xmm10, xmm11;\n"                                                                                          \
    "pmuludq xmm10, xmm12;\n"                                                                                          \
    "pmuludq xmm10, xmm13;\n"                                                                                          \
    "pmuludq xmm10, xmm14;\n"                                                                                          \
    "pmuludq xmm10, xmm15;\n"                                                                                          \
    ";\n"                                                                                                              \
    "pmuludq xmm11, xmm0;\n"                                                                                           \
    "pmuludq xmm11, xmm1;\n"                                                                                           \
    "pmuludq xmm11, xmm2;\n"                                                                                           \
    "pmuludq xmm11, xmm3;\n"                                                                                           \
    "pmuludq xmm11, xmm4;\n"                                                                                           \
    "pmuludq xmm11, xmm5;\n"                                                                                           \
    "pmuludq xmm11, xmm6;\n"                                                                                           \
    "pmuludq xmm11, xmm7;\n"                                                                                           \
    "pmuludq xmm11, xmm8;\n"                                                                                           \
    "pmuludq xmm11, xmm9;\n"                                                                                           \
    "pmuludq xmm11, xmm10;\n"                                                                                          \
    "pmuludq xmm11, xmm11;\n"                                                                                          \
    "pmuludq xmm11, xmm12;\n"                                                                                          \
    "pmuludq xmm11, xmm13;\n"                                                                                          \
    "pmuludq xmm11, xmm14;\n"                                                                                          \
    "pmuludq xmm11, xmm15;\n"                                                                                          \
    ";\n"                                                                                                              \
    "pmuludq xmm12, xmm0;\n"                                                                                           \
    "pmuludq xmm12, xmm1;\n"                                                                                           \
    "pmuludq xmm12, xmm2;\n"                                                                                           \
    "pmuludq xmm12, xmm3;\n"                                                                                           \
    "pmuludq xmm12, xmm4;\n"                                                                                           \
    "pmuludq xmm12, xmm5;\n"                                                                                           \
    "pmuludq xmm12, xmm6;\n"                                                                                           \
    "pmuludq xmm12, xmm7;\n"                                                                                           \
    "pmuludq xmm12, xmm8;\n"                                                                                           \
    "pmuludq xmm12, xmm9;\n"                                                                                           \
    "pmuludq xmm12, xmm10;\n"                                                                                          \
    "pmuludq xmm12, xmm11;\n"                                                                                          \
    "pmuludq xmm12, xmm12;\n"                                                                                          \
    "pmuludq xmm12, xmm13;\n"                                                                                          \
    "pmuludq xmm12, xmm14;\n"                                                                                          \
    "pmuludq xmm12, xmm15;\n"                                                                                          \
    ";\n"                                                                                                              \
    "pmuludq xmm13, xmm0;\n"                                                                                           \
    "pmuludq xmm13, xmm1;\n"                                                                                           \
    "pmuludq xmm13, xmm2;\n"                                                                                           \
    "pmuludq xmm13, xmm3;\n"                                                                                           \
    "pmuludq xmm13, xmm4;\n"                                                                                           \
    "pmuludq xmm13, xmm5;\n"                                                                                           \
    "pmuludq xmm13, xmm6;\n"                                                                                           \
    "pmuludq xmm13, xmm7;\n"                                                                                           \
    "pmuludq xmm13, xmm8;\n"                                                                                           \
    "pmuludq xmm13, xmm9;\n"                                                                                           \
    "pmuludq xmm13, xmm10;\n"                                                                                          \
    "pmuludq xmm13, xmm11;\n"                                                                                          \
    "pmuludq xmm13, xmm12;\n"                                                                                          \
    "pmuludq xmm13, xmm13;\n"                                                                                          \
    "pmuludq xmm13, xmm14;\n"                                                                                          \
    "pmuludq xmm13, xmm15;\n"                                                                                          \
    ";\n"                                                                                                              \
    "pmuludq xmm14, xmm0;\n"                                                                                           \
    "pmuludq xmm14, xmm1;\n"                                                                                           \
    "pmuludq xmm14, xmm2;\n"                                                                                           \
    "pmuludq xmm14, xmm3;\n"                                                                                           \
    "pmuludq xmm14, xmm4;\n"                                                                                           \
    "pmuludq xmm14, xmm5;\n"                                                                                           \
    "pmuludq xmm14, xmm6;\n"                                                                                           \
    "pmuludq xmm14, xmm7;\n"                                                                                           \
    "pmuludq xmm14, xmm8;\n"                                                                                           \
    "pmuludq xmm14, xmm9;\n"                                                                                           \
    "pmuludq xmm14, xmm10;\n"                                                                                          \
    "pmuludq xmm14, xmm11;\n"                                                                                          \
    "pmuludq xmm14, xmm12;\n"                                                                                          \
    "pmuludq xmm14, xmm13;\n"                                                                                          \
    "pmuludq xmm14, xmm14;\n"                                                                                          \
    "pmuludq xmm14, xmm15;\n"                                                                                          \
    ";\n"                                                                                                              \
    "pmuludq xmm0, xmm0;\n"                                                                                            \
    "pmuludq xmm0, xmm1;\n"                                                                                            \
    "pmuludq xmm0, xmm2;\n"                                                                                            \
    "pmuludq xmm0, xmm3;\n"                                                                                            \
    "pmuludq xmm0, xmm4;\n"                                                                                            \
    "pmuludq xmm0, xmm5;\n"                                                                                            \
    "pmuludq xmm0, xmm6;\n"                                                                                            \
    "pmuludq xmm0, xmm7;\n"                                                                                            \
    "pmuludq xmm0, xmm8;\n"                                                                                            \
    "pmuludq xmm0, xmm9;\n"                                                                                            \
    "pmuludq xmm0, xmm10;\n"                                                                                           \
    "pmuludq xmm0, xmm11;\n"                                                                                           \
    "pmuludq xmm0, xmm12;\n"                                                                                           \
    "pmuludq xmm0, xmm13;\n"                                                                                           \
    "pmuludq xmm0, xmm14;\n"                                                                                           \
    "pmuludq xmm0, xmm15;\n" 
