#define CODE                                                                                                           \
    ";\n"                                                                                                              \
    "movq xmm0, rax;\n"                                                                                                \
    "movq xmm0, rcx;\n"                                                                                                \
    "movq xmm0, rdx;\n"                                                                                                \
    "movq xmm0, rbx;\n"                                                                                                \
    "movq xmm0, rsp;\n"                                                                                                \
    "movq xmm0, rbp;\n"                                                                                                \
    "movq xmm0, rsi;\n"                                                                                                \
    "movq xmm0, rdi;\n"                                                                                                \
    "movq xmm0, r8;\n"                                                                                                 \
    "movq xmm0, r9;\n"                                                                                                 \
    "movq xmm0, r10;\n"                                                                                                \
    "movq xmm0, r11;\n"                                                                                                \
    "movq xmm0, r12;\n"                                                                                                \
    "movq xmm0, r13;\n"                                                                                                \
    "movq xmm0, r14;\n"                                                                                                \
    "movq xmm0, r15;\n"                                                                                                \
    ";\n"                                                                                                              \
    "movq xmm1, rax;\n"                                                                                                \
    "movq xmm1, rcx;\n"                                                                                                \
    "movq xmm1, rdx;\n"                                                                                                \
    "movq xmm1, rbx;\n"                                                                                                \
    "movq xmm1, rsp;\n"                                                                                                \
    "movq xmm1, rbp;\n"                                                                                                \
    "movq xmm1, rsi;\n"                                                                                                \
    "movq xmm1, rdi;\n"                                                                                                \
    "movq xmm1, r8;\n"                                                                                                 \
    "movq xmm1, r9;\n"                                                                                                 \
    "movq xmm1, r10;\n"                                                                                                \
    "movq xmm1, r11;\n"                                                                                                \
    "movq xmm1, r12;\n"                                                                                                \
    "movq xmm1, r13;\n"                                                                                                \
    "movq xmm1, r14;\n"                                                                                                \
    "movq xmm1, r15;\n"                                                                                                \
    ";\n"                                                                                                              \
    "movq xmm2, rax;\n"                                                                                                \
    "movq xmm2, rcx;\n"                                                                                                \
    "movq xmm2, rdx;\n"                                                                                                \
    "movq xmm2, rbx;\n"                                                                                                \
    "movq xmm2, rsp;\n"                                                                                                \
    "movq xmm2, rbp;\n"                                                                                                \
    "movq xmm2, rsi;\n"                                                                                                \
    "movq xmm2, rdi;\n"                                                                                                \
    "movq xmm2, r8;\n"                                                                                                 \
    "movq xmm2, r9;\n"                                                                                                 \
    "movq xmm2, r10;\n"                                                                                                \
    "movq xmm2, r11;\n"                                                                                                \
    "movq xmm2, r12;\n"                                                                                                \
    "movq xmm2, r13;\n"                                                                                                \
    "movq xmm2, r14;\n"                                                                                                \
    "movq xmm2, r15;\n"                                                                                                \
    ";\n"                                                                                                              \
    "movq xmm2, [rax+0xee];\n"                                                                                         \
    "movq xmm2, [rcx+0xdd];\n"                                                                                         \
    "movq xmm2, [rdx+0x8efde];\n"                                                                                      \
    "movq xmm2, [rbx+0x4cd];\n"                                                                                        \
    "movq xmm2, [rsp+0xaa];\n"                                                                                         \
    "movq xmm2, [rbp+0xff];\n"                                                                                         \
    "movq xmm2, [rsi+0xfddd];\n"                                                                                       \
    "movq xmm2, [rdi+0xabcd];\n"                                                                                       \
    "movq xmm2, [r8+0x9a9a9];\n"                                                                                       \
    "movq xmm2, [r9+0x456];\n"                                                                                         \
    "movq xmm2, [r10+0x123];\n"                                                                                        \
    "movq xmm2, [r11+0x89dd];\n"                                                                                       \
    "movq xmm2, [r12+0x9a34];\n"                                                                                       \
    "movq xmm2, [r13+0xffff];\n"                                                                                       \
    "movq xmm2, [r14+0x4edf];\n"                                                                                       \
    "movq xmm2, [r15+0xfe];\n"                                                                                         \
    ";\n"                                                                                                              \
    "movq xmm3, rax;\n"                                                                                                \
    "movq xmm3, rcx;\n"                                                                                                \
    "movq xmm3, rdx;\n"                                                                                                \
    "movq xmm3, rbx;\n"                                                                                                \
    "movq xmm3, rsp;\n"                                                                                                \
    "movq xmm3, rbp;\n"                                                                                                \
    "movq xmm3, rsi;\n"                                                                                                \
    "movq xmm3, rdi;\n"                                                                                                \
    "movq xmm3, r8;\n"                                                                                                 \
    "movq xmm3, r9;\n"                                                                                                 \
    "movq xmm3, r10;\n"                                                                                                \
    "movq xmm3, r11;\n"                                                                                                \
    "movq xmm3, r12;\n"                                                                                                \
    "movq xmm3, r13;\n"                                                                                                \
    "movq xmm3, r14;\n"                                                                                                \
    "movq xmm3, r15;\n"                                                                                                \
    ";\n"                                                                                                              \
    "movq xmm4, rax;\n"                                                                                                \
    "movq xmm4, rcx;\n"                                                                                                \
    "movq xmm4, rdx;\n"                                                                                                \
    "movq xmm4, rbx;\n"                                                                                                \
    "movq xmm4, rsp;\n"                                                                                                \
    "movq xmm4, rbp;\n"                                                                                                \
    "movq xmm4, rsi;\n"                                                                                                \
    "movq xmm4, rdi;\n"                                                                                                \
    "movq xmm4, r8;\n"                                                                                                 \
    "movq xmm4, r9;\n"                                                                                                 \
    "movq xmm4, r10;\n"                                                                                                \
    "movq xmm4, r11;\n"                                                                                                \
    "movq xmm4, r12;\n"                                                                                                \
    "movq xmm4, r13;\n"                                                                                                \
    "movq xmm4, r14;\n"                                                                                                \
    "movq xmm4, r15;\n"                                                                                                \
    ";\n"                                                                                                              \
    "movq xmm5, rax;\n"                                                                                                \
    "movq xmm5, rcx;\n"                                                                                                \
    "movq xmm5, rdx;\n"                                                                                                \
    "movq xmm5, rbx;\n"                                                                                                \
    "movq xmm5, rsp;\n"                                                                                                \
    "movq xmm5, rbp;\n"                                                                                                \
    "movq xmm5, rsi;\n"                                                                                                \
    "movq xmm5, rdi;\n"                                                                                                \
    "movq xmm5, r8;\n"                                                                                                 \
    "movq xmm5, r9;\n"                                                                                                 \
    "movq xmm5, r10;\n"                                                                                                \
    "movq xmm5, r11;\n"                                                                                                \
    "movq xmm5, r12;\n"                                                                                                \
    "movq xmm5, r13;\n"                                                                                                \
    "movq xmm5, r14;\n"                                                                                                \
    "movq xmm5, r15;\n"                                                                                                \
    ";\n"                                                                                                              \
    "movq xmm6, rax;\n"                                                                                                \
    "movq xmm6, rcx;\n"                                                                                                \
    "movq xmm6, rdx;\n"                                                                                                \
    "movq xmm6, rbx;\n"                                                                                                \
    "movq xmm6, rsp;\n"                                                                                                \
    "movq xmm6, rbp;\n"                                                                                                \
    "movq xmm6, rsi;\n"                                                                                                \
    "movq xmm6, rdi;\n"                                                                                                \
    "movq xmm6, r8;\n"                                                                                                 \
    "movq xmm6, r9;\n"                                                                                                 \
    "movq xmm6, r10;\n"                                                                                                \
    "movq xmm6, r11;\n"                                                                                                \
    "movq xmm6, r12;\n"                                                                                                \
    "movq xmm6, r13;\n"                                                                                                \
    "movq xmm6, r14;\n"                                                                                                \
    "movq xmm6, r15;\n"                                                                                                \
    ";\n"                                                                                                              \
    "movq xmm7, rax;\n"                                                                                                \
    "movq xmm7, rcx;\n"                                                                                                \
    "movq xmm7, rdx;\n"                                                                                                \
    "movq xmm7, rbx;\n"                                                                                                \
    "movq xmm7, rsp;\n"                                                                                                \
    "movq xmm7, rbp;\n"                                                                                                \
    "movq xmm7, rsi;\n"                                                                                                \
    "movq xmm7, rdi;\n"                                                                                                \
    "movq xmm7, r8;\n"                                                                                                 \
    "movq xmm7, r9;\n"                                                                                                 \
    "movq xmm7, r10;\n"                                                                                                \
    "movq xmm7, r11;\n"                                                                                                \
    "movq xmm7, r12;\n"                                                                                                \
    "movq xmm7, r13;\n"                                                                                                \
    "movq xmm7, r14;\n"                                                                                                \
    "movq xmm7, r15;\n"                                                                                                \
    ";\n"                                                                                                              \
    "movq xmm8, rax;\n"                                                                                                \
    "movq xmm8, rcx;\n"                                                                                                \
    "movq xmm8, rdx;\n"                                                                                                \
    "movq xmm8, rbx;\n"                                                                                                \
    "movq xmm8, rsp;\n"                                                                                                \
    "movq xmm8, rbp;\n"                                                                                                \
    "movq xmm8, rsi;\n"                                                                                                \
    "movq xmm8, rdi;\n"                                                                                                \
    "movq xmm8, r8;\n"                                                                                                 \
    "movq xmm8, r9;\n"                                                                                                 \
    "movq xmm8, r10;\n"                                                                                                \
    "movq xmm8, r11;\n"                                                                                                \
    "movq xmm8, r12;\n"                                                                                                \
    "movq xmm8, r13;\n"                                                                                                \
    "movq xmm8, r14;\n"                                                                                                \
    "movq xmm8, r15;\n"                                                                                                \
    ";\n"                                                                                                              \
    "movq xmm9, rax;\n"                                                                                                \
    "movq xmm9, rcx;\n"                                                                                                \
    "movq xmm9, rdx;\n"                                                                                                \
    "movq xmm9, rbx;\n"                                                                                                \
    "movq xmm9, rsp;\n"                                                                                                \
    "movq xmm9, rbp;\n"                                                                                                \
    "movq xmm9, rsi;\n"                                                                                                \
    "movq xmm9, rdi;\n"                                                                                                \
    "movq xmm9, r8;\n"                                                                                                 \
    "movq xmm9, r9;\n"                                                                                                 \
    "movq xmm9, r10;\n"                                                                                                \
    "movq xmm9, r11;\n"                                                                                                \
    "movq xmm9, r12;\n"                                                                                                \
    "movq xmm9, r13;\n"                                                                                                \
    "movq xmm9, r14;\n"                                                                                                \
    "movq xmm9, r15;\n"                                                                                                \
    ";\n"                                                                                                              \
    ";\n"                                                                                                              \
    "movq xmm10, rax;\n"                                                                                               \
    "movq xmm10, rcx;\n"                                                                                               \
    "movq xmm10, rdx;\n"                                                                                               \
    "movq xmm10, rbx;\n"                                                                                               \
    "movq xmm10, rsp;\n"                                                                                               \
    "movq xmm10, rbp;\n"                                                                                               \
    "movq xmm10, rsi;\n"                                                                                               \
    "movq xmm10, rdi;\n"                                                                                               \
    "movq xmm10, r8;\n"                                                                                                \
    "movq xmm10, r9;\n"                                                                                                \
    "movq xmm10, r10;\n"                                                                                               \
    "movq xmm10, r11;\n"                                                                                               \
    "movq xmm10, r12;\n"                                                                                               \
    "movq xmm10, r13;\n"                                                                                               \
    "movq xmm10, r14;\n"                                                                                               \
    "movq xmm10, r15;\n"                                                                                               \
    ";\n"                                                                                                              \
    "movq xmm11, rax;\n"                                                                                               \
    "movq xmm11, rcx;\n"                                                                                               \
    "movq xmm11, rdx;\n"                                                                                               \
    "movq xmm11, rbx;\n"                                                                                               \
    "movq xmm11, rsp;\n"                                                                                               \
    "movq xmm11, rbp;\n"                                                                                               \
    "movq xmm11, rsi;\n"                                                                                               \
    "movq xmm11, rdi;\n"                                                                                               \
    "movq xmm11, r8;\n"                                                                                                \
    "movq xmm11, r9;\n"                                                                                                \
    "movq xmm11, r10;\n"                                                                                               \
    "movq xmm11, r11;\n"                                                                                               \
    "movq xmm11, r12;\n"                                                                                               \
    "movq xmm11, r13;\n"                                                                                               \
    "movq xmm11, r14;\n"                                                                                               \
    "movq xmm11, r15;\n"                                                                                               \
    ";\n"                                                                                                              \
    ";\n"                                                                                                              \
    "movq xmm11, [rax+0xee];\n"                                                                                        \
    "movq xmm11, [rcx+0xdd];\n"                                                                                        \
    "movq xmm11, [rdx+0x8efde];\n"                                                                                     \
    "movq xmm11, [rbx+0x4cd];\n"                                                                                       \
    "movq xmm11, [rsp+0xaa];\n"                                                                                        \
    "movq xmm11, [rbp+0xff];\n"                                                                                        \
    "movq xmm11, [rsi+0xfddd];\n"                                                                                      \
    "movq xmm11, [rdi+0xabcd];\n"                                                                                      \
    "movq xmm11, [r8+0x9a9a9];\n"                                                                                      \
    "movq xmm11, [r9+0x456];\n"                                                                                        \
    "movq xmm11, [r10+0x123];\n"                                                                                       \
    "movq xmm11, [r11+0x89dd];\n"                                                                                      \
    "movq xmm11, [r12+0x9a34];\n"                                                                                      \
    "movq xmm11, [r13+0xffff];\n"                                                                                      \
    "movq xmm11, [r14+0x4edf];\n"                                                                                      \
    "movq xmm11, [r15+0xfe];\n"                                                                                        \
    ";\n"                                                                                                              \
    "movq xmm12, rax;\n"                                                                                               \
    "movq xmm12, rcx;\n"                                                                                               \
    "movq xmm12, rdx;\n"                                                                                               \
    "movq xmm12, rbx;\n"                                                                                               \
    "movq xmm12, rsp;\n"                                                                                               \
    "movq xmm12, rbp;\n"                                                                                               \
    "movq xmm12, rsi;\n"                                                                                               \
    "movq xmm12, rdi;\n"                                                                                               \
    "movq xmm12, r8;\n"                                                                                                \
    "movq xmm12, r9;\n"                                                                                                \
    "movq xmm12, r10;\n"                                                                                               \
    "movq xmm12, r11;\n"                                                                                               \
    "movq xmm12, r12;\n"                                                                                               \
    "movq xmm12, r13;\n"                                                                                               \
    "movq xmm12, r14;\n"                                                                                               \
    "movq xmm12, r15;\n"                                                                                               \
    ";\n"                                                                                                              \
    "movq xmm13, rax;\n"                                                                                               \
    "movq xmm13, rcx;\n"                                                                                               \
    "movq xmm13, rdx;\n"                                                                                               \
    "movq xmm13, rbx;\n"                                                                                               \
    "movq xmm13, rsp;\n"                                                                                               \
    "movq xmm13, rbp;\n"                                                                                               \
    "movq xmm13, rsi;\n"                                                                                               \
    "movq xmm13, rdi;\n"                                                                                               \
    "movq xmm13, r8;\n"                                                                                                \
    "movq xmm13, r9;\n"                                                                                                \
    "movq xmm13, r10;\n"                                                                                               \
    "movq xmm13, r11;\n"                                                                                               \
    "movq xmm13, r12;\n"                                                                                               \
    "movq xmm13, r13;\n"                                                                                               \
    "movq xmm13, r14;\n"                                                                                               \
    "movq xmm13, r15;\n"                                                                                               \
    ";\n"                                                                                                              \
    "movq xmm14, rax;\n"                                                                                               \
    "movq xmm14, rcx;\n"                                                                                               \
    "movq xmm14, rdx;\n"                                                                                               \
    "movq xmm14, rbx;\n"                                                                                               \
    "movq xmm14, rsp;\n"                                                                                               \
    "movq xmm14, rbp;\n"                                                                                               \
    "movq xmm14, rsi;\n"                                                                                               \
    "movq xmm14, rdi;\n"                                                                                               \
    "movq xmm14, r8;\n"                                                                                                \
    "movq xmm14, r9;\n"                                                                                                \
    "movq xmm14, r10;\n"                                                                                               \
    "movq xmm14, r11;\n"                                                                                               \
    "movq xmm14, r12;\n"                                                                                               \
    "movq xmm14, r13;\n"                                                                                               \
    "movq xmm14, r14;\n"                                                                                               \
    "movq xmm14, r15;\n"                                                                                               \
    ";\n"                                                                                                              \
    "movq xmm15, rax;\n"                                                                                               \
    "movq xmm15, rcx;\n"                                                                                               \
    "movq xmm15, rdx;\n"                                                                                               \
    "movq xmm15, rbx;\n"                                                                                               \
    "movq xmm15, rsp;\n"                                                                                               \
    "movq xmm15, rbp;\n"                                                                                               \
    "movq xmm15, rsi;\n"                                                                                               \
    "movq xmm15, rdi;\n"                                                                                               \
    "movq xmm15, r8;\n"                                                                                                \
    "movq xmm15, r9;\n"                                                                                                \
    "movq xmm15, r10;\n"                                                                                               \
    "movq xmm15, r11;\n"                                                                                               \
    "movq xmm15, r12;\n"                                                                                               \
    "movq xmm15, r13;\n"                                                                                               \
    "movq xmm15, r14;\n"                                                                                               \
    "movq xmm15, r15;\n"                                                                                               \
    ";\n"                                                                                                              \
    ";\n"                                                                                                              \
    ";\n"                                                                                                              \
    "movq xmm0, xmm0;\n"                                                                                               \
    "movq xmm0, xmm1;\n"                                                                                               \
    "movq xmm0, xmm2;\n"                                                                                               \
    "movq xmm0, xmm3;\n"                                                                                               \
    "movq xmm0, xmm4;\n"                                                                                               \
    "movq xmm0, xmm5;\n"                                                                                               \
    "movq xmm0, xmm6;\n"                                                                                               \
    "movq xmm0, xmm7;\n"                                                                                               \
    "movq xmm0, xmm8;\n"                                                                                               \
    "movq xmm0, xmm9;\n"                                                                                               \
    "movq xmm0, xmm10;\n"                                                                                              \
    "movq xmm0, xmm11;\n"                                                                                              \
    "movq xmm0, xmm12;\n"                                                                                              \
    "movq xmm0, xmm13;\n"                                                                                              \
    "movq xmm0, xmm14;\n"                                                                                              \
    "movq xmm0, xmm15;\n"                                                                                              \
    ";\n"                                                                                                              \
    "movq xmm1, xmm0;\n"                                                                                               \
    "movq xmm1, xmm1;\n"                                                                                               \
    "movq xmm1, xmm2;\n"                                                                                               \
    "movq xmm1, xmm3;\n"                                                                                               \
    "movq xmm1, xmm4;\n"                                                                                               \
    "movq xmm1, xmm5;\n"                                                                                               \
    "movq xmm1, xmm6;\n"                                                                                               \
    "movq xmm1, xmm7;\n"                                                                                               \
    "movq xmm1, xmm8;\n"                                                                                               \
    "movq xmm1, xmm9;\n"                                                                                               \
    "movq xmm1, xmm10;\n"                                                                                              \
    "movq xmm1, xmm11;\n"                                                                                              \
    "movq xmm1, xmm12;\n"                                                                                              \
    "movq xmm1, xmm13;\n"                                                                                              \
    "movq xmm1, xmm14;\n"                                                                                              \
    "movq xmm1, xmm15;\n"                                                                                              \
    ";\n"                                                                                                              \
    "movq xmm2, xmm0;\n"                                                                                               \
    "movq xmm2, xmm1;\n"                                                                                               \
    "movq xmm2, xmm2;\n"                                                                                               \
    "movq xmm2, xmm3;\n"                                                                                               \
    "movq xmm2, xmm4;\n"                                                                                               \
    "movq xmm2, xmm5;\n"                                                                                               \
    "movq xmm2, xmm6;\n"                                                                                               \
    "movq xmm2, xmm7;\n"                                                                                               \
    "movq xmm2, xmm8;\n"                                                                                               \
    "movq xmm2, xmm9;\n"                                                                                               \
    "movq xmm2, xmm10;\n"                                                                                              \
    "movq xmm2, xmm11;\n"                                                                                              \
    "movq xmm2, xmm12;\n"                                                                                              \
    "movq xmm2, xmm13;\n"                                                                                              \
    "movq xmm2, xmm14;\n"                                                                                              \
    "movq xmm2, xmm15;\n"                                                                                              \
    ";\n"                                                                                                              \
    "movq xmm3, xmm0;\n"                                                                                               \
    "movq xmm3, xmm1;\n"                                                                                               \
    "movq xmm3, xmm2;\n"                                                                                               \
    "movq xmm3, xmm3;\n"                                                                                               \
    "movq xmm3, xmm4;\n"                                                                                               \
    "movq xmm3, xmm5;\n"                                                                                               \
    "movq xmm3, xmm6;\n"                                                                                               \
    "movq xmm3, xmm7;\n"                                                                                               \
    "movq xmm3, xmm8;\n"                                                                                               \
    "movq xmm3, xmm9;\n"                                                                                               \
    "movq xmm3, xmm10;\n"                                                                                              \
    "movq xmm3, xmm11;\n"                                                                                              \
    "movq xmm3, xmm12;\n"                                                                                              \
    "movq xmm3, xmm13;\n"                                                                                              \
    "movq xmm3, xmm14;\n"                                                                                              \
    "movq xmm3, xmm15;\n"                                                                                              \
    ";\n"                                                                                                              \
    "movq xmm4, xmm0;\n"                                                                                               \
    "movq xmm4, xmm1;\n"                                                                                               \
    "movq xmm4, xmm2;\n"                                                                                               \
    "movq xmm4, xmm3;\n"                                                                                               \
    "movq xmm4, xmm4;\n"                                                                                               \
    "movq xmm4, xmm5;\n"                                                                                               \
    "movq xmm4, xmm6;\n"                                                                                               \
    "movq xmm4, xmm7;\n"                                                                                               \
    "movq xmm4, xmm8;\n"                                                                                               \
    "movq xmm4, xmm9;\n"                                                                                               \
    "movq xmm4, xmm10;\n"                                                                                              \
    "movq xmm4, xmm11;\n"                                                                                              \
    "movq xmm4, xmm12;\n"                                                                                              \
    "movq xmm4, xmm13;\n"                                                                                              \
    "movq xmm4, xmm14;\n"                                                                                              \
    "movq xmm4, xmm15;\n"                                                                                              \
    ";\n"                                                                                                              \
    "movq xmm5, xmm0;\n"                                                                                               \
    "movq xmm5, xmm1;\n"                                                                                               \
    "movq xmm5, xmm2;\n"                                                                                               \
    "movq xmm5, xmm3;\n"                                                                                               \
    "movq xmm5, xmm4;\n"                                                                                               \
    "movq xmm5, xmm5;\n"                                                                                               \
    "movq xmm5, xmm6;\n"                                                                                               \
    "movq xmm5, xmm7;\n"                                                                                               \
    "movq xmm5, xmm8;\n"                                                                                               \
    "movq xmm5, xmm9;\n"                                                                                               \
    "movq xmm5, xmm10;\n"                                                                                              \
    "movq xmm5, xmm11;\n"                                                                                              \
    "movq xmm5, xmm12;\n"                                                                                              \
    "movq xmm5, xmm13;\n"                                                                                              \
    "movq xmm5, xmm14;\n"                                                                                              \
    "movq xmm5, xmm15;\n"                                                                                              \
    ";\n"                                                                                                              \
    "movq xmm6, xmm0;\n"                                                                                               \
    "movq xmm6, xmm1;\n"                                                                                               \
    "movq xmm6, xmm2;\n"                                                                                               \
    "movq xmm6, xmm3;\n"                                                                                               \
    "movq xmm6, xmm4;\n"                                                                                               \
    "movq xmm6, xmm5;\n"                                                                                               \
    "movq xmm6, xmm6;\n"                                                                                               \
    "movq xmm6, xmm7;\n"                                                                                               \
    "movq xmm6, xmm8;\n"                                                                                               \
    "movq xmm6, xmm9;\n"                                                                                               \
    "movq xmm6, xmm10;\n"                                                                                              \
    "movq xmm6, xmm11;\n"                                                                                              \
    "movq xmm6, xmm12;\n"                                                                                              \
    "movq xmm6, xmm13;\n"                                                                                              \
    "movq xmm6, xmm14;\n"                                                                                              \
    "movq xmm6, xmm15;\n"                                                                                              \
    ";\n"                                                                                                              \
    "movq xmm7, xmm0;\n"                                                                                               \
    "movq xmm7, xmm1;\n"                                                                                               \
    "movq xmm7, xmm2;\n"                                                                                               \
    "movq xmm7, xmm3;\n"                                                                                               \
    "movq xmm7, xmm4;\n"                                                                                               \
    "movq xmm7, xmm5;\n"                                                                                               \
    "movq xmm7, xmm6;\n"                                                                                               \
    "movq xmm7, xmm7;\n"                                                                                               \
    "movq xmm7, xmm8;\n"                                                                                               \
    "movq xmm7, xmm9;\n"                                                                                               \
    "movq xmm7, xmm10;\n"                                                                                              \
    "movq xmm7, xmm11;\n"                                                                                              \
    "movq xmm7, xmm12;\n"                                                                                              \
    "movq xmm7, xmm13;\n"                                                                                              \
    "movq xmm7, xmm14;\n"                                                                                              \
    "movq xmm7, xmm15;\n"                                                                                              \
    ";\n"                                                                                                              \
    "movq xmm8, xmm0;\n"                                                                                               \
    "movq xmm8, xmm1;\n"                                                                                               \
    "movq xmm8, xmm2;\n"                                                                                               \
    "movq xmm8, xmm3;\n"                                                                                               \
    "movq xmm8, xmm4;\n"                                                                                               \
    "movq xmm8, xmm5;\n"                                                                                               \
    "movq xmm8, xmm6;\n"                                                                                               \
    "movq xmm8, xmm7;\n"                                                                                               \
    "movq xmm8, xmm8;\n"                                                                                               \
    "movq xmm8, xmm9;\n"                                                                                               \
    "movq xmm8, xmm10;\n"                                                                                              \
    "movq xmm8, xmm11;\n"                                                                                              \
    "movq xmm8, xmm12;\n"                                                                                              \
    "movq xmm8, xmm13;\n"                                                                                              \
    "movq xmm8, xmm14;\n"                                                                                              \
    "movq xmm8, xmm15;\n"                                                                                              \
    ";\n"                                                                                                              \
    "movq xmm9, xmm0;\n"                                                                                               \
    "movq xmm9, xmm1;\n"                                                                                               \
    "movq xmm9, xmm2;\n"                                                                                               \
    "movq xmm9, xmm3;\n"                                                                                               \
    "movq xmm9, xmm4;\n"                                                                                               \
    "movq xmm9, xmm5;\n"                                                                                               \
    "movq xmm9, xmm6;\n"                                                                                               \
    "movq xmm9, xmm7;\n"                                                                                               \
    "movq xmm9, xmm8;\n"                                                                                               \
    "movq xmm9, xmm9;\n"                                                                                               \
    "movq xmm9, xmm10;\n"                                                                                              \
    "movq xmm9, xmm11;\n"                                                                                              \
    "movq xmm9, xmm12;\n"                                                                                              \
    "movq xmm9, xmm13;\n"                                                                                              \
    "movq xmm9, xmm14;\n"                                                                                              \
    "movq xmm9, xmm15;\n"                                                                                              \
    ";\n"                                                                                                              \
    "movq xmm10, xmm0;\n"                                                                                              \
    "movq xmm10, xmm1;\n"                                                                                              \
    "movq xmm10, xmm2;\n"                                                                                              \
    "movq xmm10, xmm3;\n"                                                                                              \
    "movq xmm10, xmm4;\n"                                                                                              \
    "movq xmm10, xmm5;\n"                                                                                              \
    "movq xmm10, xmm6;\n"                                                                                              \
    "movq xmm10, xmm7;\n"                                                                                              \
    "movq xmm10, xmm8;\n"                                                                                              \
    "movq xmm10, xmm9;\n"                                                                                              \
    "movq xmm10, xmm10;\n"                                                                                             \
    "movq xmm10, xmm11;\n"                                                                                             \
    "movq xmm10, xmm12;\n"                                                                                             \
    "movq xmm10, xmm13;\n"                                                                                             \
    "movq xmm10, xmm14;\n"                                                                                             \
    "movq xmm10, xmm15;\n"                                                                                             \
    ";\n"                                                                                                              \
    "movq xmm11, xmm0;\n"                                                                                              \
    "movq xmm11, xmm1;\n"                                                                                              \
    "movq xmm11, xmm2;\n"                                                                                              \
    "movq xmm11, xmm3;\n"                                                                                              \
    "movq xmm11, xmm4;\n"                                                                                              \
    "movq xmm11, xmm5;\n"                                                                                              \
    "movq xmm11, xmm6;\n"                                                                                              \
    "movq xmm11, xmm7;\n"                                                                                              \
    "movq xmm11, xmm8;\n"                                                                                              \
    "movq xmm11, xmm9;\n"                                                                                              \
    "movq xmm11, xmm10;\n"                                                                                             \
    "movq xmm11, xmm11;\n"                                                                                             \
    "movq xmm11, xmm12;\n"                                                                                             \
    "movq xmm11, xmm13;\n"                                                                                             \
    "movq xmm11, xmm14;\n"                                                                                             \
    "movq xmm11, xmm15;\n"                                                                                             \
    ";\n"                                                                                                              \
    "movq xmm12, xmm0;\n"                                                                                              \
    "movq xmm12, xmm1;\n"                                                                                              \
    "movq xmm12, xmm2;\n"                                                                                              \
    "movq xmm12, xmm3;\n"                                                                                              \
    "movq xmm12, xmm4;\n"                                                                                              \
    "movq xmm12, xmm5;\n"                                                                                              \
    "movq xmm12, xmm6;\n"                                                                                              \
    "movq xmm12, xmm7;\n"                                                                                              \
    "movq xmm12, xmm8;\n"                                                                                              \
    "movq xmm12, xmm9;\n"                                                                                              \
    "movq xmm12, xmm10;\n"                                                                                             \
    "movq xmm12, xmm11;\n"                                                                                             \
    "movq xmm12, xmm12;\n"                                                                                             \
    "movq xmm12, xmm13;\n"                                                                                             \
    "movq xmm12, xmm14;\n"                                                                                             \
    "movq xmm12, xmm15;\n"                                                                                             \
    ";\n"                                                                                                              \
    "movq xmm13, xmm0;\n"                                                                                              \
    "movq xmm13, xmm1;\n"                                                                                              \
    "movq xmm13, xmm2;\n"                                                                                              \
    "movq xmm13, xmm3;\n"                                                                                              \
    "movq xmm13, xmm4;\n"                                                                                              \
    "movq xmm13, xmm5;\n"                                                                                              \
    "movq xmm13, xmm6;\n"                                                                                              \
    "movq xmm13, xmm7;\n"                                                                                              \
    "movq xmm13, xmm8;\n"                                                                                              \
    "movq xmm13, xmm9;\n"                                                                                              \
    "movq xmm13, xmm10;\n"                                                                                             \
    "movq xmm13, xmm11;\n"                                                                                             \
    "movq xmm13, xmm12;\n"                                                                                             \
    "movq xmm13, xmm13;\n"                                                                                             \
    "movq xmm13, xmm14;\n"                                                                                             \
    "movq xmm13, xmm15;\n"                                                                                             \
    ";\n"                                                                                                              \
    "movq xmm14, xmm0;\n"                                                                                              \
    "movq xmm14, xmm1;\n"                                                                                              \
    "movq xmm14, xmm2;\n"                                                                                              \
    "movq xmm14, xmm3;\n"                                                                                              \
    "movq xmm14, xmm4;\n"                                                                                              \
    "movq xmm14, xmm5;\n"                                                                                              \
    "movq xmm14, xmm6;\n"                                                                                              \
    "movq xmm14, xmm7;\n"                                                                                              \
    "movq xmm14, xmm8;\n"                                                                                              \
    "movq xmm14, xmm9;\n"                                                                                              \
    "movq xmm14, xmm10;\n"                                                                                             \
    "movq xmm14, xmm11;\n"                                                                                             \
    "movq xmm14, xmm12;\n"                                                                                             \
    "movq xmm14, xmm13;\n"                                                                                             \
    "movq xmm14, xmm14;\n"                                                                                             \
    "movq xmm14, xmm15;\n"                                                                                             \
    ";\n"                                                                                                              \
    "movq xmm0, xmm0;\n"                                                                                               \
    "movq xmm0, xmm1;\n"                                                                                               \
    "movq xmm0, xmm2;\n"                                                                                               \
    "movq xmm0, xmm3;\n"                                                                                               \
    "movq xmm0, xmm4;\n"                                                                                               \
    "movq xmm0, xmm5;\n"                                                                                               \
    "movq xmm0, xmm6;\n"                                                                                               \
    "movq xmm0, xmm7;\n"                                                                                               \
    "movq xmm0, xmm8;\n"                                                                                               \
    "movq xmm0, xmm9;\n"                                                                                               \
    "movq xmm0, xmm10;\n"                                                                                              \
    "movq xmm0, xmm11;\n"                                                                                              \
    "movq xmm0, xmm12;\n"                                                                                              \
    "movq xmm0, xmm13;\n"                                                                                              \
    "movq xmm0, xmm14;\n"                                                                                              \
    "movq xmm0, xmm15;\n"                                                                                              \
    ""
