#define CODE                                                                                                           \
    "shl r10, 0x1;\n"                                                                                                  \
    "shl r10, 0x12;\n"                                                                                                 \
    "shl r10, 0x14;\n"                                                                                                 \
    "shl r10, 0x15;\n"                                                                                                 \
    "shl r10, 0x1b;\n"                                                                                                 \
    "shl r10, 0x1c;\n"                                                                                                 \
    "shl r10, 0x2;\n"                                                                                                  \
    "shl r10, 0x24;\n"                                                                                                 \
    "shl r10, 0x27;\n"                                                                                                 \
    "shl r10, 0x29;\n"                                                                                                 \
    "shl r10, 0x2b;\n"                                                                                                 \
    "shl r10, 0x2d;\n"                                                                                                 \
    "shl r10, 0x3;\n"                                                                                                  \
    "shl r10, 0x37;\n"                                                                                                 \
    "shl r10, 0x3d;\n"                                                                                                 \
    "shl r10, 0x6;\n"                                                                                                  \
    "shl r10, 0x8;\n"                                                                                                  \
    "shl r10, 0xa;\n"                                                                                                  \
    "shl r10, 0xe;\n"                                                                                                  \
    "shl r11, 0x1;\n"                                                                                                  \
    "shl r11, 0x12;\n"                                                                                                 \
    "shl r11, 0x14;\n"                                                                                                 \
    "shl r11, 0x15;\n"                                                                                                 \
    "shl r11, 0x19;\n"                                                                                                 \
    "shl r11, 0x1b;\n"                                                                                                 \
    "shl r11, 0x1c;\n"                                                                                                 \
    "shl r11, 0x2;\n"                                                                                                  \
    "shl r11, 0x24;\n"                                                                                                 \
    "shl r11, 0x27;\n"                                                                                                 \
    "shl r11, 0x29;\n"                                                                                                 \
    "shl r11, 0x2b;\n"                                                                                                 \
    "shl r11, 0x2c;\n"                                                                                                 \
    "shl r11, 0x2d;\n"                                                                                                 \
    "shl r11, 0x3;\n"                                                                                                  \
    "shl r11, 0x37;\n"                                                                                                 \
    "shl r11, 0x3e;\n"                                                                                                 \
    "shl r11, 0x6;\n"                                                                                                  \
    "shl r11, 0x8;\n"                                                                                                  \
    "shl r11, 0xa;\n"                                                                                                  \
    "shl r11, 0xf;\n"                                                                                                  \
    "shl r12, 0x1;\n"                                                                                                  \
    "shl r12, 0x12;\n"                                                                                                 \
    "shl r12, 0x14;\n"                                                                                                 \
    "shl r12, 0x15;\n"                                                                                                 \
    "shl r12, 0x19;\n"                                                                                                 \
    "shl r12, 0x1b;\n"                                                                                                 \
    "shl r12, 0x1c;\n"                                                                                                 \
    "shl r12, 0x29;\n"                                                                                                 \
    "shl r12, 0x3;\n"                                                                                                  \
    "shl r12, 0x3d;\n"                                                                                                 \
    "shl r12, 0x3e;\n"                                                                                                 \
    "shl r12, 0x6;\n"                                                                                                  \
    "shl r12, 0x8;\n"                                                                                                  \
    "shl r12, 0xe;\n"                                                                                                  \
    "shl r12, 0xf;\n"                                                                                                  \
    "shl r13, 0x1;\n"                                                                                                  \
    "shl r13, 0x12;\n"                                                                                                 \
    "shl r13, 0x14;\n"                                                                                                 \
    "shl r13, 0x19;\n"                                                                                                 \
    "shl r13, 0x1b;\n"                                                                                                 \
    "shl r13, 0x2;\n"                                                                                                  \
    "shl r13, 0x24;\n"                                                                                                 \
    "shl r13, 0x27;\n"                                                                                                 \
    "shl r13, 0x29;\n"                                                                                                 \
    "shl r13, 0x2b;\n"                                                                                                 \
    "shl r13, 0x2c;\n"                                                                                                 \
    "shl r13, 0x2d;\n"                                                                                                 \
    "shl r13, 0x37;\n"                                                                                                 \
    "shl r13, 0x38;\n"                                                                                                 \
    "shl r13, 0x3d;\n"                                                                                                 \
    "shl r13, 0x3e;\n"                                                                                                 \
    "shl r13, 0x6;\n"                                                                                                  \
    "shl r13, 0x8;\n"                                                                                                  \
    "shl r13, 0xa;\n"                                                                                                  \
    "shl r13, 0xe;\n"                                                                                                  \
    "shl r13, 0xf;\n"                                                                                                  \
    "shl r14, 0x1;\n"                                                                                                  \
    "shl r14, 0x12;\n"                                                                                                 \
    "shl r14, 0x14;\n"                                                                                                 \
    "shl r14, 0x15;\n"                                                                                                 \
    "shl r14, 0x19;\n"                                                                                                 \
    "shl r14, 0x1b;\n"                                                                                                 \
    "shl r14, 0x1c;\n"                                                                                                 \
    "shl r14, 0x2;\n"                                                                                                  \
    "shl r14, 0x24;\n"                                                                                                 \
    "shl r14, 0x27;\n"                                                                                                 \
    "shl r14, 0x29;\n"                                                                                                 \
    "shl r14, 0x2b;\n"                                                                                                 \
    "shl r14, 0x2c;\n"                                                                                                 \
    "shl r14, 0x2d;\n"                                                                                                 \
    "shl r14, 0x3;\n"                                                                                                  \
    "shl r14, 0x37;\n"                                                                                                 \
    "shl r14, 0x38;\n"                                                                                                 \
    "shl r14, 0x3e;\n"                                                                                                 \
    "shl r14, 0x8;\n"                                                                                                  \
    "shl r14, 0xa;\n"                                                                                                  \
    "shl r14, 0xe;\n"                                                                                                  \
    "shl r15, 0x1;\n"                                                                                                  \
    "shl r15, 0x12;\n"                                                                                                 \
    "shl r15, 0x14;\n"                                                                                                 \
    "shl r15, 0x15;\n"                                                                                                 \
    "shl r15, 0x1b;\n"                                                                                                 \
    "shl r15, 0x1c;\n"                                                                                                 \
    "shl r15, 0x2;\n"                                                                                                  \
    "shl r15, 0x24;\n"                                                                                                 \
    "shl r15, 0x27;\n"                                                                                                 \
    "shl r15, 0x2b;\n"                                                                                                 \
    "shl r15, 0x2c;\n"                                                                                                 \
    "shl r15, 0x3;\n"                                                                                                  \
    "shl r15, 0x37;\n"                                                                                                 \
    "shl r15, 0x38;\n"                                                                                                 \
    "shl r15, 0x3d;\n"                                                                                                 \
    "shl r15, 0x6;\n"                                                                                                  \
    "shl r15, 0xa;\n"                                                                                                  \
    "shl r15, 0xe;\n"                                                                                                  \
    "shl r15, 0xf;\n"                                                                                                  \
    "shl r8, 0x1;\n"                                                                                                   \
    "shl r8, 0x14;\n"                                                                                                  \
    "shl r8, 0x15;\n"                                                                                                  \
    "shl r8, 0x19;\n"                                                                                                  \
    "shl r8, 0x1b;\n"                                                                                                  \
    "shl r8, 0x1c;\n"                                                                                                  \
    "shl r8, 0x2;\n"                                                                                                   \
    "shl r8, 0x24;\n"                                                                                                  \
    "shl r8, 0x27;\n"                                                                                                  \
    "shl r8, 0x29;\n"                                                                                                  \
    "shl r8, 0x2b;\n"                                                                                                  \
    "shl r8, 0x2c;\n"                                                                                                  \
    "shl r8, 0x3;\n"                                                                                                   \
    "shl r8, 0x37;\n"                                                                                                  \
    "shl r8, 0x38;\n"                                                                                                  \
    "shl r8, 0x3d;\n"                                                                                                  \
    "shl r8, 0x3e;\n"                                                                                                  \
    "shl r8, 0x6;\n"                                                                                                   \
    "shl r8, 0x8;\n"                                                                                                   \
    "shl r8, 0xa;\n"                                                                                                   \
    "shl r8, 0xe;\n"                                                                                                   \
    "shl r8, 0xf;\n"                                                                                                   \
    "shl r9, 0x1;\n"                                                                                                   \
    "shl r9, 0x12;\n"                                                                                                  \
    "shl r9, 0x14;\n"                                                                                                  \
    "shl r9, 0x15;\n"                                                                                                  \
    "shl r9, 0x19;\n"                                                                                                  \
    "shl r9, 0x1b;\n"                                                                                                  \
    "shl r9, 0x1c;\n"                                                                                                  \
    "shl r9, 0x2;\n"                                                                                                   \
    "shl r9, 0x27;\n"                                                                                                  \
    "shl r9, 0x29;\n"                                                                                                  \
    "shl r9, 0x2b;\n"                                                                                                  \
    "shl r9, 0x2c;\n"                                                                                                  \
    "shl r9, 0x3;\n"                                                                                                   \
    "shl r9, 0x37;\n"                                                                                                  \
    "shl r9, 0x38;\n"                                                                                                  \
    "shl r9, 0x3d;\n"                                                                                                  \
    "shl r9, 0x3e;\n"                                                                                                  \
    "shl r9, 0x6;\n"                                                                                                   \
    "shl r9, 0xa;\n"                                                                                                   \
    "shl r9, 0xe;\n"                                                                                                   \
    "shl r9, 0xf;\n"                                                                                                   \
    "shl rax, 0x1;\n"                                                                                                  \
    "shl rax, 0x12;\n"                                                                                                 \
    "shl rax, 0x14;\n"                                                                                                 \
    "shl rax, 0x15;\n"                                                                                                 \
    "shl rax, 0x19;\n"                                                                                                 \
    "shl rax, 0x1b;\n"                                                                                                 \
    "shl rax, 0x1c;\n"                                                                                                 \
    "shl rax, 0x24;\n"                                                                                                 \
    "shl rax, 0x27;\n"                                                                                                 \
    "shl rax, 0x29;\n"                                                                                                 \
    "shl rax, 0x2b;\n"                                                                                                 \
    "shl rax, 0x2c;\n"                                                                                                 \
    "shl rax, 0x2d;\n"                                                                                                 \
    "shl rax, 0x3;\n"                                                                                                  \
    "shl rax, 0x37;\n"                                                                                                 \
    "shl rax, 0x38;\n"                                                                                                 \
    "shl rax, 0x3d;\n"                                                                                                 \
    "shl rax, 0x3e;\n"                                                                                                 \
    "shl rax, 0x6;\n"                                                                                                  \
    "shl rax, 0x8;\n"                                                                                                  \
    "shl rax, 0xa;\n"                                                                                                  \
    "shl rax, 0xe;\n"                                                                                                  \
    "shl rax, 0xf;\n"                                                                                                  \
    "shl rbp, 0x1;\n"                                                                                                  \
    "shl rbp, 0x12;\n"                                                                                                 \
    "shl rbp, 0x14;\n"                                                                                                 \
    "shl rbp, 0x15;\n"                                                                                                 \
    "shl rbp, 0x19;\n"                                                                                                 \
    "shl rbp, 0x1c;\n"                                                                                                 \
    "shl rbp, 0x2;\n"                                                                                                  \
    "shl rbp, 0x24;\n"                                                                                                 \
    "shl rbp, 0x27;\n"                                                                                                 \
    "shl rbp, 0x2b;\n"                                                                                                 \
    "shl rbp, 0x2c;\n"                                                                                                 \
    "shl rbp, 0x2d;\n"                                                                                                 \
    "shl rbp, 0x3;\n"                                                                                                  \
    "shl rbp, 0x37;\n"                                                                                                 \
    "shl rbp, 0x38;\n"                                                                                                 \
    "shl rbp, 0x3d;\n"                                                                                                 \
    "shl rbp, 0x3e;\n"                                                                                                 \
    "shl rbp, 0x6;\n"                                                                                                  \
    "shl rbp, 0x8;\n"                                                                                                  \
    "shl rbp, 0xa;\n"                                                                                                  \
    "shl rbp, 0xe;\n"                                                                                                  \
    "shl rbp, 0xf;\n"                                                                                                  \
    "shl rbx, 0x1;\n"                                                                                                  \
    "shl rbx, 0x14;\n"                                                                                                 \
    "shl rbx, 0x15;\n"                                                                                                 \
    "shl rbx, 0x1b;\n"                                                                                                 \
    "shl rbx, 0x1c;\n"                                                                                                 \
    "shl rbx, 0x2;\n"                                                                                                  \
    "shl rbx, 0x24;\n"                                                                                                 \
    "shl rbx, 0x27;\n"                                                                                                 \
    "shl rbx, 0x29;\n"                                                                                                 \
    "shl rbx, 0x2b;\n"                                                                                                 \
    "shl rbx, 0x2c;\n"                                                                                                 \
    "shl rbx, 0x2d;\n"                                                                                                 \
    "shl rbx, 0x3;\n"                                                                                                  \
    "shl rbx, 0x37;\n"                                                                                                 \
    "shl rbx, 0x38;\n"                                                                                                 \
    "shl rbx, 0x3e;\n"                                                                                                 \
    "shl rbx, 0x6;\n"                                                                                                  \
    "shl rbx, 0x8;\n"                                                                                                  \
    "shl rbx, 0xe;\n"                                                                                                  \
    "shl rbx, 0xf;\n"                                                                                                  \
    "shl rcx, 0x1;\n"                                                                                                  \
    "shl rcx, 0x12;\n"                                                                                                 \
    "shl rcx, 0x19;\n"                                                                                                 \
    "shl rcx, 0x1b;\n"                                                                                                 \
    "shl rcx, 0x1c;\n"                                                                                                 \
    "shl rcx, 0x2;\n"                                                                                                  \
    "shl rcx, 0x24;\n"                                                                                                 \
    "shl rcx, 0x27;\n"                                                                                                 \
    "shl rcx, 0x29;\n"                                                                                                 \
    "shl rcx, 0x2b;\n"                                                                                                 \
    "shl rcx, 0x2c;\n"                                                                                                 \
    "shl rcx, 0x3;\n"                                                                                                  \
    "shl rcx, 0x38;\n"                                                                                                 \
    "shl rcx, 0x3d;\n"                                                                                                 \
    "shl rcx, 0x3e;\n"                                                                                                 \
    "shl rcx, 0x6;\n"                                                                                                  \
    "shl rcx, 0xa;\n"                                                                                                  \
    "shl rcx, 0xf;\n"                                                                                                  \
    "shl rdi, 0x1;\n"                                                                                                  \
    "shl rdi, 0x12;\n"                                                                                                 \
    "shl rdi, 0x14;\n"                                                                                                 \
    "shl rdi, 0x19;\n"                                                                                                 \
    "shl rdi, 0x1b;\n"                                                                                                 \
    "shl rdi, 0x1c;\n"                                                                                                 \
    "shl rdi, 0x2;\n"                                                                                                  \
    "shl rdi, 0x24;\n"                                                                                                 \
    "shl rdi, 0x27;\n"                                                                                                 \
    "shl rdi, 0x29;\n"                                                                                                 \
    "shl rdi, 0x2c;\n"                                                                                                 \
    "shl rdi, 0x2d;\n"                                                                                                 \
    "shl rdi, 0x3;\n"                                                                                                  \
    "shl rdi, 0x37;\n"                                                                                                 \
    "shl rdi, 0x38;\n"                                                                                                 \
    "shl rdi, 0x3d;\n"                                                                                                 \
    "shl rdi, 0x3e;\n"                                                                                                 \
    "shl rdi, 0x6;\n"                                                                                                  \
    "shl rdi, 0x8;\n"                                                                                                  \
    "shl rdi, 0xa;\n"                                                                                                  \
    "shl rdi, 0xf;\n"                                                                                                  \
    "shl rdx, 0x1;\n"                                                                                                  \
    "shl rdx, 0x12;\n"                                                                                                 \
    "shl rdx, 0x14;\n"                                                                                                 \
    "shl rdx, 0x19;\n"                                                                                                 \
    "shl rdx, 0x1c;\n"                                                                                                 \
    "shl rdx, 0x2;\n"                                                                                                  \
    "shl rdx, 0x24;\n"                                                                                                 \
    "shl rdx, 0x27;\n"                                                                                                 \
    "shl rdx, 0x29;\n"                                                                                                 \
    "shl rdx, 0x2b;\n"                                                                                                 \
    "shl rdx, 0x2d;\n"                                                                                                 \
    "shl rdx, 0x3;\n"                                                                                                  \
    "shl rdx, 0x37;\n"                                                                                                 \
    "shl rdx, 0x38;\n"                                                                                                 \
    "shl rdx, 0x3d;\n"                                                                                                 \
    "shl rdx, 0x3e;\n"                                                                                                 \
    "shl rdx, 0x6;\n"                                                                                                  \
    "shl rdx, 0x8;\n"                                                                                                  \
    "shl rdx, 0xa;\n"                                                                                                  \
    "shl rdx, 0xf;\n"                                                                                                  \
    "shl rsi, 0x1;\n"                                                                                                  \
    "shl rsi, 0x12;\n"                                                                                                 \
    "shl rsi, 0x15;\n"                                                                                                 \
    "shl rsi, 0x19;\n"                                                                                                 \
    "shl rsi, 0x1b;\n"                                                                                                 \
    "shl rsi, 0x1c;\n"                                                                                                 \
    "shl rsi, 0x24;\n"                                                                                                 \
    "shl rsi, 0x27;\n"                                                                                                 \
    "shl rsi, 0x29;\n"                                                                                                 \
    "shl rsi, 0x2b;\n"                                                                                                 \
    "shl rsi, 0x2c;\n"                                                                                                 \
    "shl rsi, 0x2d;\n"                                                                                                 \
    "shl rsi, 0x37;\n"                                                                                                 \
    "shl rsi, 0x38;\n"                                                                                                 \
    "shl rsi, 0x3d;\n"                                                                                                 \
    "shl rsi, 0x3e;\n"                                                                                                 \
    "shl rsi, 0x6;\n"                                                                                                  \
    "shl rsi, 0x8;\n"                                                                                                  \
    "shl rsi, 0xa;\n"                                                                                                  \
    "shl rsi, 0xe;\n"                                                                                                  \
    "shl rsi, 0xf;\n"                                                                                                  \
    ""
