#define CODE                                                                                                           \
    "adc al, 0x0; \n"                                                                                                  \
    "adc ax, 0xe1; \n"                                                                                                 \
    "adc eax, 0xe11; \n"                                                                                               \
    "adc sil, 0x0; \n"                                                                                                 \
    "adc si, 0xe1; \n"                                                                                                 \
    "adc esi, 0xe11; \n"                                                                                               \
    "adc rax, 0xfffee12; \n"                                                                                           \
    "adc rax, 0xff6ee12; \n"                                                                                           \
    "adc rax, 0xf66ee12; \n"                                                                                           \
    "adc rax, 0x666ee12; \n"                                                                                           \
    "adc rax, 0x6666ee12; \n"                                                                                          \
    "adc rax, -0x1; \n"                                                                                                \
    "adc rax, -0xfffee12; \n"                                                                                          \
    "adc rax, -0xff6ee12; \n"                                                                                          \
    "adc rax, -0xf66ee12; \n"                                                                                          \
    "adc rax, -0x666ee12; \n"                                                                                          \
    "adc rax, -0x6666ee12; \n"                                                                                         \
    "adc rbp, -0xfffee12; \n"                                                                                          \
    "adc rbp, 0xfffee12; \n"                                                                                           \
    "adc rbp, 0xff6ee12; \n"                                                                                           \
    "adc rbp, 0xf66ee12; \n"                                                                                           \
    "adc rbp, 0x666ee12; \n"                                                                                           \
    "adc rbp, 0x6666ee12; \n"                                                                                          \
    "adc rbp, -0xf; \n"                                                                                                \
    "adc rbp, -0xe; \n"                                                                                                \
    "adc rbp, -0xd; \n"                                                                                                \
    "adc rbp, -0x7; \n"                                                                                                \
    "adc rbp, -0x4; \n"                                                                                                \
    "adc rbp, -0x3; \n"                                                                                                \
    "adc rbp, -0x2; \n"                                                                                                \
    "adc rbp, -0xff; \n"                                                                                               \
    "adc rbp, -0xef; \n"                                                                                               \
    "adc rbp, -0xdf; \n"                                                                                               \
    "adc rbp, -0xcf; \n"                                                                                               \
    "adc rbp, -0xbf; \n"                                                                                               \
    "adc rbp, -0xaf; \n"                                                                                               \
    "adc rbp, -0x9f; \n"                                                                                               \
    "adc rbp, -0x8f; \n"                                                                                               \
    "adc rbp, -0x7f; \n"                                                                                               \
    "adc rbp, -0x3e; \n"                                                                                               \
    "adc rbp, -0x6f; \n"                                                                                               \
    "adc rbp, -0x5f; \n"                                                                                               \
    "adc rbp, -0x4f; \n"                                                                                               \
    "adc rbp, -0x1f; \n"                                                                                               \
    "adc rbp, -0xfa; \n"                                                                                               \
    "adc rbp, -0xf9; \n"                                                                                               \
    "adc rbp, -0xf8; \n"                                                                                               \
    "adc rbp, -0xf7; \n"                                                                                               \
    "adc rbp, -0xf6; \n"                                                                                               \
    "adc rbp, -0xf5; \n"                                                                                               \
    "adc rbp, -0xf4; \n"                                                                                               \
    "adc rbp, -0xf3; \n"                                                                                               \
    "adc rbp, -0xf2; \n"                                                                                               \
    "adc rbp, -0xf1; \n"                                                                                               \
    "adc rbp, -0xf66; \n"                                                                                              \
    "adc rbp, -0x666ee; \n"                                                                                            \
    "adc rbp, -0x6666ee12; \n"                                                                                         \
    "adc r13, -0xfffee12; \n"                                                                                          \
    "adc r13, 0xfffee12; \n"                                                                                           \
    "adc r13, 0xff6ee12; \n"                                                                                           \
    "adc r13, 0xf66ee12; \n"                                                                                           \
    "adc r13, 0x666ee12; \n"                                                                                           \
    "adc r13, 0x6666ee12; \n"                                                                                          \
    "adc r13, -0x1; \n"                                                                                                \
    "adc r13, -0xfffee12; \n"                                                                                          \
    "adc r13, -0xff6ee12; \n"                                                                                          \
    "adc r13, -0xf66ee12; \n"                                                                                          \
    "adc r13, -0x666ee12; \n"                                                                                          \
    "adc r13, -0x6666ee12; \n"                                                                                         \
    "adc rax, 0x12; \n"                                                                                                \
    "adc rax, 0xe12; \n"                                                                                               \
    "adc rax, 0x66ee12; \n"                                                                                            \
    "adc rax, 0x66ee12; \n"                                                                                            \
    "adc rax, 0x6ee12; \n"                                                                                             \
    "adc sp, 0x34ef; \n"                                                                                               \
    "adc r8w, 0x1; \n"                                                                                                 \
    "adc rax, [ rbx ]; \n"                                                                                             \
    "adc rax, [ rbx + 0x10 ]; \n"                                                                                      \
    "adc rax, 0x0 ; \n"                                                                                                \
    "adc rax, 0x0; \n"                                                                                                 \
    "adc r12, r14; \n"                                                                                                 \
    "adc r12, rbx; \n"                                                                                                 \
    "adc r12, [ rsp + 0x10 ]; \n"                                                                                      \
    "adc rax, 0xfff; \n"                                                                                               \
    "adc rax, r15; \n"                                                                                                 \
    "adc rax, rbp; \n"                                                                                                 \
    "adc rbp, r12; \n"                                                                                                 \
    "adc rbp, r8; \n"                                                                                                  \
    "adc rbp, r9; \n"                                                                                                  \
    "adc rbx, r9; \n"                                                                                                  \
    "adc rbx, rdi; \n"                                                                                                 \
    "adc rdi, r10; \n"                                                                                                 \
    "adc rdx, r14; \n"                                                                                                 \
    "adc rsp, 0x138 ; \n"                                                                                              \
    "adc rsp, 0x48 ; \n"                                                                                               \
    "adc rsp, 0x50 ; \n"                                                                                               \
    "adc rsp, 0x80 ; \n"
