#define CODE                                                                                                           \
    "por xmm0, xmm0;\n"                                                                                                \
    "por xmm0, xmm1;\n"                                                                                                \
    "por xmm0, xmm2;\n"                                                                                                \
    "por xmm0, xmm3;\n"                                                                                                \
    "por xmm0, xmm4;\n"                                                                                                \
    "por xmm0, xmm5;\n"                                                                                                \
    "por xmm0, xmm6;\n"                                                                                                \
    "por xmm0, xmm7;\n"                                                                                                \
    "por xmm1, xmm0;\n"                                                                                                \
    "por xmm1, xmm1;\n"                                                                                                \
    "por xmm1, xmm2;\n"                                                                                                \
    "por xmm1, xmm3;\n"                                                                                                \
    "por xmm1, xmm4;\n"                                                                                                \
    "por xmm1, xmm5;\n"                                                                                                \
    "por xmm1, xmm6;\n"                                                                                                \
    "por xmm1, xmm7;\n"                                                                                                \
    "por xmm2, xmm0;\n"                                                                                                \
    "por xmm2, xmm1;\n"                                                                                                \
    "por xmm2, xmm2;\n"                                                                                                \
    "por xmm2, xmm3;\n"                                                                                                \
    "por xmm2, xmm4;\n"                                                                                                \
    "por xmm2, xmm5;\n"                                                                                                \
    "por xmm2, xmm6;\n"                                                                                                \
    "por xmm2, xmm7;\n"                                                                                                \
    "por xmm3, xmm0;\n"                                                                                                \
    "por xmm3, xmm1;\n"                                                                                                \
    "por xmm3, xmm2;\n"                                                                                                \
    "por xmm3, xmm3;\n"                                                                                                \
    "por xmm3, xmm4;\n"                                                                                                \
    "por xmm3, xmm5;\n"                                                                                                \
    "por xmm3, xmm6;\n"                                                                                                \
    "por xmm3, xmm7;\n"                                                                                                \
    "por xmm4, xmm0;\n"                                                                                                \
    "por xmm4, xmm1;\n"                                                                                                \
    "por xmm4, xmm2;\n"                                                                                                \
    "por xmm4, xmm3;\n"                                                                                                \
    "por xmm4, xmm4;\n"                                                                                                \
    "por xmm4, xmm5;\n"                                                                                                \
    "por xmm4, xmm6;\n"                                                                                                \
    "por xmm4, xmm7;\n"                                                                                                \
    "por xmm5, xmm0;\n"                                                                                                \
    "por xmm5, xmm1;\n"                                                                                                \
    "por xmm5, xmm2;\n"                                                                                                \
    "por xmm5, xmm3;\n"                                                                                                \
    "por xmm5, xmm4;\n"                                                                                                \
    "por xmm5, xmm5;\n"                                                                                                \
    "por xmm5, xmm6;\n"                                                                                                \
    "por xmm5, xmm7;\n"                                                                                                \
    "por xmm6, xmm0;\n"                                                                                                \
    "por xmm6, xmm1;\n"                                                                                                \
    "por xmm6, xmm2;\n"                                                                                                \
    "por xmm6, xmm3;\n"                                                                                                \
    "por xmm6, xmm4;\n"                                                                                                \
    "por xmm6, xmm5;\n"                                                                                                \
    "por xmm6, xmm6;\n"                                                                                                \
    "por xmm6, xmm7;\n"                                                                                                \
    "por xmm7, xmm0;\n"                                                                                                \
    "por xmm7, xmm1;\n"                                                                                                \
    "por xmm7, xmm2;\n"                                                                                                \
    "por xmm7, xmm3;\n"                                                                                                \
    "por xmm7, xmm4;\n"                                                                                                \
    "por xmm7, xmm5;\n"                                                                                                \
    "por xmm7, xmm6;\n"                                                                                                \
    "por xmm7, xmm7;\n"                                                                                                \
    "por xmm8, xmm0;\n"                                                                                                \
    "por xmm8, xmm1;\n"                                                                                                \
    "por xmm8, xmm2;\n"                                                                                                \
    "por xmm8, xmm3;\n"                                                                                                \
    "por xmm8, xmm4;\n"                                                                                                \
    "por xmm8, xmm5;\n"                                                                                                \
    "por xmm8, xmm6;\n"                                                                                                \
    "por xmm8, xmm7;\n"                                                                                                \
    "por xmm0, xmm15;\n"                                                                                               \
    "por xmm1, xmm14;\n"                                                                                               \
    "por xmm2, xmm13;\n"                                                                                               \
    "por xmm3, xmm12;\n"                                                                                               \
    "por xmm4, xmm11;\n"                                                                                               \
    "por xmm5, xmm10;\n"                                                                                               \
    "por xmm6, xmm9;\n"                                                                                                \
    "por xmm7, xmm8;\n"                                                                                                \
    "por xmm8, xmm14;\n" 
