#define CODE                                                                                                           \
    "shr r10, 0x13;\n"                                                                                                 \
    "shr r10, 0x14;\n"                                                                                                 \
    "shr r10, 0x15;\n"                                                                                                 \
    "shr r10, 0x19;\n"                                                                                                 \
    "shr r10, 0x1c;\n"                                                                                                 \
    "shr r10, 0x2;\n"                                                                                                  \
    "shr r10, 0x24;\n"                                                                                                 \
    "shr r10, 0x27;\n"                                                                                                 \
    "shr r10, 0x2b;\n"                                                                                                 \
    "shr r10, 0x31;\n"                                                                                                 \
    "shr r10, 0x32;\n"                                                                                                 \
    "shr r10, 0x38;\n"                                                                                                 \
    "shr r10, 0x3e;\n"                                                                                                 \
    "shr r10, 0x3f;\n"                                                                                                 \
    "shr r10, 0x8;\n"                                                                                                  \
    "shr r10, 0x9;\n"                                                                                                  \
    "shr r11, 0x13;\n"                                                                                                 \
    "shr r11, 0x14;\n"                                                                                                 \
    "shr r11, 0x15;\n"                                                                                                 \
    "shr r11, 0x17;\n"                                                                                                 \
    "shr r11, 0x19;\n"                                                                                                 \
    "shr r11, 0x2;\n"                                                                                                  \
    "shr r11, 0x24;\n"                                                                                                 \
    "shr r11, 0x25;\n"                                                                                                 \
    "shr r11, 0x27;\n"                                                                                                 \
    "shr r11, 0x2b;\n"                                                                                                 \
    "shr r11, 0x2c;\n"                                                                                                 \
    "shr r11, 0x2e;\n"                                                                                                 \
    "shr r11, 0x3;\n"                                                                                                  \
    "shr r11, 0x31;\n"                                                                                                 \
    "shr r11, 0x32;\n"                                                                                                 \
    "shr r11, 0x3d;\n"                                                                                                 \
    "shr r11, 0x3e;\n"                                                                                                 \
    "shr r11, 0x3f;\n"                                                                                                 \
    "shr r11, 0x8;\n"                                                                                                  \
    "shr r11, 0x9;\n"                                                                                                  \
    "shr r12, 0x14;\n"                                                                                                 \
    "shr r12, 0x15;\n"                                                                                                 \
    "shr r12, 0x1c;\n"                                                                                                 \
    "shr r12, 0x2;\n"                                                                                                  \
    "shr r12, 0x24;\n"                                                                                                 \
    "shr r12, 0x25;\n"                                                                                                 \
    "shr r12, 0x27;\n"                                                                                                 \
    "shr r12, 0x2b;\n"                                                                                                 \
    "shr r12, 0x2c;\n"                                                                                                 \
    "shr r12, 0x2e;\n"                                                                                                 \
    "shr r12, 0x3;\n"                                                                                                  \
    "shr r12, 0x31;\n"                                                                                                 \
    "shr r12, 0x32;\n"                                                                                                 \
    "shr r12, 0x36;\n"                                                                                                 \
    "shr r12, 0x3a;\n"                                                                                                 \
    "shr r12, 0x3d;\n"                                                                                                 \
    "shr r12, 0x3e;\n"                                                                                                 \
    "shr r12, 0x3f;\n"                                                                                                 \
    "shr r12, 0x9;\n"                                                                                                  \
    "shr r13, 0x13;\n"                                                                                                 \
    "shr r13, 0x14;\n"                                                                                                 \
    "shr r13, 0x15;\n"                                                                                                 \
    "shr r13, 0x17;\n"                                                                                                 \
    "shr r13, 0x19;\n"                                                                                                 \
    "shr r13, 0x1c;\n"                                                                                                 \
    "shr r13, 0x2;\n"                                                                                                  \
    "shr r13, 0x24;\n"                                                                                                 \
    "shr r13, 0x25;\n"                                                                                                 \
    "shr r13, 0x27;\n"                                                                                                 \
    "shr r13, 0x2c;\n"                                                                                                 \
    "shr r13, 0x3;\n"                                                                                                  \
    "shr r13, 0x31;\n"                                                                                                 \
    "shr r13, 0x36;\n"                                                                                                 \
    "shr r13, 0x38;\n"                                                                                                 \
    "shr r13, 0x3a;\n"                                                                                                 \
    "shr r13, 0x3d;\n"                                                                                                 \
    "shr r13, 0x3e;\n"                                                                                                 \
    "shr r13, 0x3f;\n"                                                                                                 \
    "shr r13, 0x8;\n"                                                                                                  \
    "shr r14, 0x14;\n"                                                                                                 \
    "shr r14, 0x15;\n"                                                                                                 \
    "shr r14, 0x17;\n"                                                                                                 \
    "shr r14, 0x19;\n"                                                                                                 \
    "shr r14, 0x2;\n"                                                                                                  \
    "shr r14, 0x24;\n"                                                                                                 \
    "shr r14, 0x27;\n"                                                                                                 \
    "shr r14, 0x2b;\n"                                                                                                 \
    "shr r14, 0x2c;\n"                                                                                                 \
    "shr r14, 0x2e;\n"                                                                                                 \
    "shr r14, 0x3;\n"                                                                                                  \
    "shr r14, 0x31;\n"                                                                                                 \
    "shr r14, 0x38;\n"                                                                                                 \
    "shr r14, 0x3a;\n"                                                                                                 \
    "shr r14, 0x3d;\n"                                                                                                 \
    "shr r14, 0x3e;\n"                                                                                                 \
    "shr r14, 0x3f;\n"                                                                                                 \
    "shr r14, 0x8;\n"                                                                                                  \
    "shr r14, 0x9;\n"                                                                                                  \
    "shr r15, 0x13;\n"                                                                                                 \
    "shr r15, 0x14;\n"                                                                                                 \
    "shr r15, 0x15;\n"                                                                                                 \
    "shr r15, 0x17;\n"                                                                                                 \
    "shr r15, 0x19;\n"                                                                                                 \
    "shr r15, 0x1c;\n"                                                                                                 \
    "shr r15, 0x24;\n"                                                                                                 \
    "shr r15, 0x25;\n"                                                                                                 \
    "shr r15, 0x27;\n"                                                                                                 \
    "shr r15, 0x2c;\n"                                                                                                 \
    "shr r15, 0x2e;\n"                                                                                                 \
    "shr r15, 0x3;\n"                                                                                                  \
    "shr r15, 0x31;\n"                                                                                                 \
    "shr r15, 0x32;\n"                                                                                                 \
    "shr r15, 0x36;\n"                                                                                                 \
    "shr r15, 0x38;\n"                                                                                                 \
    "shr r15, 0x3a;\n"                                                                                                 \
    "shr r15, 0x3d;\n"                                                                                                 \
    "shr r15, 0x3e;\n"                                                                                                 \
    "shr r15, 0x3f;\n"                                                                                                 \
    "shr r15, 0x9;\n"                                                                                                  \
    "shr r8, 0x13;\n"                                                                                                  \
    "shr r8, 0x14;\n"                                                                                                  \
    "shr r8, 0x15;\n"                                                                                                  \
    "shr r8, 0x1c;\n"                                                                                                  \
    "shr r8, 0x2;\n"                                                                                                   \
    "shr r8, 0x24;\n"                                                                                                  \
    "shr r8, 0x25;\n"                                                                                                  \
    "shr r8, 0x27;\n"                                                                                                  \
    "shr r8, 0x2c;\n"                                                                                                  \
    "shr r8, 0x2e;\n"                                                                                                  \
    "shr r8, 0x3;\n"                                                                                                   \
    "shr r8, 0x31;\n"                                                                                                  \
    "shr r8, 0x36;\n"                                                                                                  \
    "shr r8, 0x38;\n"                                                                                                  \
    "shr r8, 0x3a;\n"                                                                                                  \
    "shr r8, 0x3d;\n"                                                                                                  \
    "shr r8, 0x3e;\n"                                                                                                  \
    "shr r8, 0x3f;\n"                                                                                                  \
    "shr r8, 0x8;\n"                                                                                                   \
    "shr r8, 0x9;\n"                                                                                                   \
    "shr r9, 0x13;\n"                                                                                                  \
    "shr r9, 0x15;\n"                                                                                                  \
    "shr r9, 0x17;\n"                                                                                                  \
    "shr r9, 0x19;\n"                                                                                                  \
    "shr r9, 0x1c;\n"                                                                                                  \
    "shr r9, 0x2;\n"                                                                                                   \
    "shr r9, 0x24;\n"                                                                                                  \
    "shr r9, 0x25;\n"                                                                                                  \
    "shr r9, 0x2b;\n"                                                                                                  \
    "shr r9, 0x2c;\n"                                                                                                  \
    "shr r9, 0x2e;\n"                                                                                                  \
    "shr r9, 0x3;\n"                                                                                                   \
    "shr r9, 0x31;\n"                                                                                                  \
    "shr r9, 0x36;\n"                                                                                                  \
    "shr r9, 0x3d;\n"                                                                                                  \
    "shr r9, 0x3e;\n"                                                                                                  \
    "shr r9, 0x3f;\n"                                                                                                  \
    "shr r9, 0x9;\n"                                                                                                   \
    "shr rax, 0x13;\n"                                                                                                 \
    "shr rax, 0x14;\n"                                                                                                 \
    "shr rax, 0x19;\n"                                                                                                 \
    "shr rax, 0x1c;\n"                                                                                                 \
    "shr rax, 0x2;\n"                                                                                                  \
    "shr rax, 0x24;\n"                                                                                                 \
    "shr rax, 0x25;\n"                                                                                                 \
    "shr rax, 0x27;\n"                                                                                                 \
    "shr rax, 0x2c;\n"                                                                                                 \
    "shr rax, 0x2e;\n"                                                                                                 \
    "shr rax, 0x3;\n"                                                                                                  \
    "shr rax, 0x31;\n"                                                                                                 \
    "shr rax, 0x32;\n"                                                                                                 \
    "shr rax, 0x36;\n"                                                                                                 \
    "shr rax, 0x38;\n"                                                                                                 \
    "shr rax, 0x3a;\n"                                                                                                 \
    "shr rax, 0x3e;\n"                                                                                                 \
    "shr rax, 0x3f;\n"                                                                                                 \
    "shr rax, 0x8;\n"                                                                                                  \
    "shr rax, 0x9;\n"                                                                                                  \
    "shr rbp, 0x14;\n"                                                                                                 \
    "shr rbp, 0x15;\n"                                                                                                 \
    "shr rbp, 0x17;\n"                                                                                                 \
    "shr rbp, 0x1c;\n"                                                                                                 \
    "shr rbp, 0x2;\n"                                                                                                  \
    "shr rbp, 0x25;\n"                                                                                                 \
    "shr rbp, 0x27;\n"                                                                                                 \
    "shr rbp, 0x2b;\n"                                                                                                 \
    "shr rbp, 0x2c;\n"                                                                                                 \
    "shr rbp, 0x2e;\n"                                                                                                 \
    "shr rbp, 0x3;\n"                                                                                                  \
    "shr rbp, 0x31;\n"                                                                                                 \
    "shr rbp, 0x32;\n"                                                                                                 \
    "shr rbp, 0x36;\n"                                                                                                 \
    "shr rbp, 0x38;\n"                                                                                                 \
    "shr rbp, 0x3d;\n"                                                                                                 \
    "shr rbp, 0x3e;\n"                                                                                                 \
    "shr rbp, 0x3f;\n"                                                                                                 \
    "shr rbp, 0x8;\n"                                                                                                  \
    "shr rbp, 0x9;\n"                                                                                                  \
    "shr rbx, 0x13;\n"                                                                                                 \
    "shr rbx, 0x17;\n"                                                                                                 \
    "shr rbx, 0x19;\n"                                                                                                 \
    "shr rbx, 0x2;\n"                                                                                                  \
    "shr rbx, 0x24;\n"                                                                                                 \
    "shr rbx, 0x25;\n"                                                                                                 \
    "shr rbx, 0x27;\n"                                                                                                 \
    "shr rbx, 0x2c;\n"                                                                                                 \
    "shr rbx, 0x2e;\n"                                                                                                 \
    "shr rbx, 0x3;\n"                                                                                                  \
    "shr rbx, 0x32;\n"                                                                                                 \
    "shr rbx, 0x36;\n"                                                                                                 \
    "shr rbx, 0x3d;\n"                                                                                                 \
    "shr rbx, 0x3e;\n"                                                                                                 \
    "shr rbx, 0x3f;\n"                                                                                                 \
    "shr rbx, 0x9;\n"                                                                                                  \
    "shr rcx, 0x13;\n"                                                                                                 \
    "shr rcx, 0x15;\n"                                                                                                 \
    "shr rcx, 0x17;\n"                                                                                                 \
    "shr rcx, 0x19;\n"                                                                                                 \
    "shr rcx, 0x2;\n"                                                                                                  \
    "shr rcx, 0x24;\n"                                                                                                 \
    "shr rcx, 0x25;\n"                                                                                                 \
    "shr rcx, 0x2c;\n"                                                                                                 \
    "shr rcx, 0x2e;\n"                                                                                                 \
    "shr rcx, 0x3;\n"                                                                                                  \
    "shr rcx, 0x32;\n"                                                                                                 \
    "shr rcx, 0x38;\n"                                                                                                 \
    "shr rcx, 0x3a;\n"                                                                                                 \
    "shr rcx, 0x3d;\n"                                                                                                 \
    "shr rcx, 0x3e;\n"                                                                                                 \
    "shr rcx, 0x3f;\n"                                                                                                 \
    "shr rcx, 0x8;\n"                                                                                                  \
    "shr rcx, 0x9;\n"                                                                                                  \
    "shr rdi, 0x14;\n"                                                                                                 \
    "shr rdi, 0x15;\n"                                                                                                 \
    "shr rdi, 0x17;\n"                                                                                                 \
    "shr rdi, 0x1c;\n"                                                                                                 \
    "shr rdi, 0x2;\n"                                                                                                  \
    "shr rdi, 0x24;\n"                                                                                                 \
    "shr rdi, 0x25;\n"                                                                                                 \
    "shr rdi, 0x27;\n"                                                                                                 \
    "shr rdi, 0x2b;\n"                                                                                                 \
    "shr rdi, 0x2c;\n"                                                                                                 \
    "shr rdi, 0x2e;\n"                                                                                                 \
    "shr rdi, 0x3;\n"                                                                                                  \
    "shr rdi, 0x32;\n"                                                                                                 \
    "shr rdi, 0x36;\n"                                                                                                 \
    "shr rdi, 0x38;\n"                                                                                                 \
    "shr rdi, 0x3a;\n"                                                                                                 \
    "shr rdi, 0x3d;\n"                                                                                                 \
    "shr rdi, 0x3f;\n"                                                                                                 \
    "shr rdi, 0x8;\n"                                                                                                  \
    "shr rdx, 0x13;\n"                                                                                                 \
    "shr rdx, 0x14;\n"                                                                                                 \
    "shr rdx, 0x15;\n"                                                                                                 \
    "shr rdx, 0x17;\n"                                                                                                 \
    "shr rdx, 0x19;\n"                                                                                                 \
    "shr rdx, 0x1c;\n"                                                                                                 \
    "shr rdx, 0x2;\n"                                                                                                  \
    "shr rdx, 0x24;\n"                                                                                                 \
    "shr rdx, 0x25;\n"                                                                                                 \
    "shr rdx, 0x27;\n"                                                                                                 \
    "shr rdx, 0x2b;\n"                                                                                                 \
    "shr rdx, 0x2c;\n"                                                                                                 \
    "shr rdx, 0x2e;\n"                                                                                                 \
    "shr rdx, 0x31;\n"                                                                                                 \
    "shr rdx, 0x32;\n"                                                                                                 \
    "shr rdx, 0x36;\n"                                                                                                 \
    "shr rdx, 0x38;\n"                                                                                                 \
    "shr rdx, 0x3d;\n"                                                                                                 \
    "shr rdx, 0x3e;\n"                                                                                                 \
    "shr rdx, 0x3f;\n"                                                                                                 \
    "shr rdx, 0x8;\n"                                                                                                  \
    "shr rdx, 0x9;\n"                                                                                                  \
    "shr rsi, 0x14;\n"                                                                                                 \
    "shr rsi, 0x15;\n"                                                                                                 \
    "shr rsi, 0x17;\n"                                                                                                 \
    "shr rsi, 0x19;\n"                                                                                                 \
    "shr rsi, 0x1c;\n"                                                                                                 \
    "shr rsi, 0x24;\n"                                                                                                 \
    "shr rsi, 0x25;\n"                                                                                                 \
    "shr rsi, 0x27;\n"                                                                                                 \
    "shr rsi, 0x2b;\n"                                                                                                 \
    "shr rsi, 0x2c;\n"                                                                                                 \
    "shr rsi, 0x2e;\n"                                                                                                 \
    "shr rsi, 0x3;\n"                                                                                                  \
    "shr rsi, 0x32;\n"                                                                                                 \
    "shr rsi, 0x36;\n"                                                                                                 \
    "shr rsi, 0x38;\n"                                                                                                 \
    "shr rsi, 0x3a;\n"                                                                                                 \
    "shr rsi, 0x3d;\n"                                                                                                 \
    "shr rsi, 0x3e;\n"                                                                                                 \
    "shr rsi, 0x3f;\n"                                                                                                 \
    "shr rsi, 0x9;\n"                                                                                                  \
    "shr r13, 51;\n"                                                                                                   \
    "shr r14, 51;\n"                                                                                                   \
    "shr r9, 51;\n"                                                                                                    \
    "shr rbp, 51;\n"                                                                                                   \
    "shr r10, 51;\n"                                                                                                   \
    ""
