#define CODE                                                                                                           \
    "seta al;\n"                                                                                                       \
    "setae cl;\n"                                                                                                      \
    "setb dl;\n"                                                                                                       \
    "setbe bl;\n"                                                                                                      \
    "setc spl;\n"                                                                                                      \
    "sete bpl;\n"                                                                                                      \
    "setg sil;\n"                                                                                                      \
    "setge dil;\n"                                                                                                     \
    "setl r8b;\n"                                                                                                      \
    "setle r9b;\n"                                                                                                     \
    "setna r10b;\n"                                                                                                    \
    "setnae r11b;\n"                                                                                                   \
    "setnb r12b;\n"                                                                                                    \
    "setnbe r13b;\n"                                                                                                   \
    "setnc r14b;\n"                                                                                                    \
    "setne r15b;\n"                                                                                                    \
    "setng al;\n"                                                                                                      \
    "setnge cl;\n"                                                                                                     \
    "setnl dl;\n"                                                                                                      \
    "setnle bl;\n"                                                                                                     \
    "setno spl;\n"                                                                                                     \
    "setnp bpl;\n"                                                                                                     \
    "setns sil;\n"                                                                                                     \
    "setnz dil;\n"                                                                                                     \
    "seto r8b;\n"                                                                                                      \
    "setp r9b;\n"                                                                                                      \
    "setpe r10b;\n"                                                                                                    \
    "setpo r11b;\n"                                                                                                    \
    "sets r12b;\n"                                                                                                     \
    "setz r13b;\n"                                                                                                     \
    "seta [rax];\n"                                                                                                    \
    "setae [rcx];\n"                                                                                                   \
    "setb [rdx];\n"                                                                                                    \
    "setbe [rbx];\n"                                                                                                   \
    "setc [rsp];\n"                                                                                                    \
    "sete [rbp];\n"                                                                                                    \
    "setg [rsi];\n"                                                                                                    \
    "setge [rdi];\n"                                                                                                   \
    "setl [r8];\n"                                                                                                     \
    "setle [r9];\n"                                                                                                    \
    "setna [r10];\n"                                                                                                   \
    "setnae [r11];\n"                                                                                                  \
    "setnb [r12];\n"                                                                                                   \
    "setnbe [r13];\n"                                                                                                  \
    "setnc [r14];\n"                                                                                                   \
    "setne [r15];\n"                                                                                                   \
    "setng [eax];\n"                                                                                                   \
    "setnge [ecx];\n"                                                                                                  \
    "setnl [edx];\n"                                                                                                   \
    "setnle [ebx];\n"                                                                                                  \
    "setno [esp];\n"                                                                                                   \
    "setnp [ebp];\n"                                                                                                   \
    "setns [esi];\n"                                                                                                   \
    "setnz [edi];\n"                                                                                                   \
    "seto [r8d];\n"                                                                                                    \
    "setp [r9d];\n"                                                                                                    \
    "setpe [r10d];\n"                                                                                                  \
    "setpo [r11d];\n"                                                                                                  \
    "sets [r12d];\n"                                                                                                   \
    "setz [r13d];\n" 
