#define CODE                                                                                                           \
    ";\n"                                                                                                              \
    "movd xmm0, eax;\n"                                                                                                \
    "movd xmm0, ecx;\n"                                                                                                \
    "movd xmm0, edx;\n"                                                                                                \
    "movd xmm0, ebx;\n"                                                                                                \
    "movd xmm0, esp;\n"                                                                                                \
    "movd xmm0, ebp;\n"                                                                                                \
    "movd xmm0, esi;\n"                                                                                                \
    "movd xmm0, edi;\n"                                                                                                \
    "movd xmm0, r8d;\n"                                                                                                \
    "movd xmm0, r9d;\n"                                                                                                \
    "movd xmm0, r10d;\n"                                                                                               \
    "movd xmm0, r11d;\n"                                                                                               \
    "movd xmm0, r12d;\n"                                                                                               \
    "movd xmm0, r13d;\n"                                                                                               \
    "movd xmm0, r14d;\n"                                                                                               \
    "movd xmm0, r15d;\n"                                                                                               \
    "movd ebx, xmm0;\n"                                                                                                \
    "movd r14d, xmm0;\n"                                                                                               \
    ";\n"                                                                                                              \
    "movd xmm1, eax;\n"                                                                                                \
    "movd xmm1, ecx;\n"                                                                                                \
    "movd xmm1, edx;\n"                                                                                                \
    "movd xmm1, ebx;\n"                                                                                                \
    "movd xmm1, esp;\n"                                                                                                \
    "movd xmm1, ebp;\n"                                                                                                \
    "movd xmm1, esi;\n"                                                                                                \
    "movd xmm1, edi;\n"                                                                                                \
    "movd xmm1, r8d;\n"                                                                                                \
    "movd xmm1, r9d;\n"                                                                                                \
    "movd xmm1, r10d;\n"                                                                                               \
    "movd xmm1, r11d;\n"                                                                                               \
    "movd xmm1, r12d;\n"                                                                                               \
    "movd xmm1, r13d;\n"                                                                                               \
    "movd xmm1, r14d;\n"                                                                                               \
    "movd xmm1, r15d;\n"                                                                                               \
    "movd ebx, xmm1;\n"                                                                                                \
    "movd r14d, xmm1;\n"                                                                                               \
    ";\n"                                                                                                              \
    "movd xmm2, eax;\n"                                                                                                \
    "movd xmm2, ecx;\n"                                                                                                \
    "movd xmm2, edx;\n"                                                                                                \
    "movd xmm2, ebx;\n"                                                                                                \
    "movd xmm2, esp;\n"                                                                                                \
    "movd xmm2, ebp;\n"                                                                                                \
    "movd xmm2, esi;\n"                                                                                                \
    "movd xmm2, edi;\n"                                                                                                \
    "movd xmm2, r8d;\n"                                                                                                \
    "movd xmm2, r9d;\n"                                                                                                \
    "movd xmm2, r10d;\n"                                                                                               \
    "movd xmm2, r11d;\n"                                                                                               \
    "movd xmm2, r12d;\n"                                                                                               \
    "movd xmm2, r13d;\n"                                                                                               \
    "movd xmm2, r14d;\n"                                                                                               \
    "movd xmm2, r15d;\n"                                                                                               \
    "movd ebx, xmm2;\n"                                                                                                \
    "movd r14d, xmm2;\n"                                                                                               \
    ";\n"                                                                                                              \
    "movd xmm3, eax;\n"                                                                                                \
    "movd xmm3, ecx;\n"                                                                                                \
    "movd xmm3, edx;\n"                                                                                                \
    "movd xmm3, ebx;\n"                                                                                                \
    "movd xmm3, esp;\n"                                                                                                \
    "movd xmm3, ebp;\n"                                                                                                \
    "movd xmm3, esi;\n"                                                                                                \
    "movd xmm3, edi;\n"                                                                                                \
    "movd xmm3, r8d;\n"                                                                                                \
    "movd xmm3, r9d;\n"                                                                                                \
    "movd xmm3, r10d;\n"                                                                                               \
    "movd xmm3, r11d;\n"                                                                                               \
    "movd xmm3, r12d;\n"                                                                                               \
    "movd xmm3, r13d;\n"                                                                                               \
    "movd xmm3, r14d;\n"                                                                                               \
    "movd xmm3, r15d;\n"                                                                                               \
    "movd ebx, xmm3;\n"                                                                                                \
    "movd r14d, xmm3;\n"                                                                                               \
    ";\n"                                                                                                              \
    "movd xmm4, eax;\n"                                                                                                \
    "movd xmm4, ecx;\n"                                                                                                \
    "movd xmm4, edx;\n"                                                                                                \
    "movd xmm4, ebx;\n"                                                                                                \
    "movd xmm4, esp;\n"                                                                                                \
    "movd xmm4, ebp;\n"                                                                                                \
    "movd xmm4, esi;\n"                                                                                                \
    "movd xmm4, edi;\n"                                                                                                \
    "movd xmm4, r8d;\n"                                                                                                \
    "movd xmm4, r9d;\n"                                                                                                \
    "movd xmm4, r10d;\n"                                                                                               \
    "movd xmm4, r11d;\n"                                                                                               \
    "movd xmm4, r12d;\n"                                                                                               \
    "movd xmm4, r13d;\n"                                                                                               \
    "movd xmm4, r14d;\n"                                                                                               \
    "movd xmm4, r15d;\n"                                                                                               \
    "movd ebx, xmm4;\n"                                                                                                \
    "movd r14d, xmm4;\n"                                                                                               \
    ";\n"                                                                                                              \
    "movd xmm5, eax;\n"                                                                                                \
    "movd xmm5, ecx;\n"                                                                                                \
    "movd xmm5, edx;\n"                                                                                                \
    "movd xmm5, ebx;\n"                                                                                                \
    "movd xmm5, esp;\n"                                                                                                \
    "movd xmm5, ebp;\n"                                                                                                \
    "movd xmm5, esi;\n"                                                                                                \
    "movd xmm5, edi;\n"                                                                                                \
    "movd xmm5, r8d;\n"                                                                                                \
    "movd xmm5, r9d;\n"                                                                                                \
    "movd xmm5, r10d;\n"                                                                                               \
    "movd xmm5, r11d;\n"                                                                                               \
    "movd xmm5, r12d;\n"                                                                                               \
    "movd xmm5, r13d;\n"                                                                                               \
    "movd xmm5, r14d;\n"                                                                                               \
    "movd xmm5, r15d;\n"                                                                                               \
    "movd ebx, xmm5;\n"                                                                                                \
    "movd r14d, xmm5;\n"                                                                                               \
    ";\n"                                                                                                              \
    "movd xmm5, [rax];\n"                                                                                              \
    "movd xmm5, [rcx];\n"                                                                                              \
    "movd xmm5, [rdx];\n"                                                                                              \
    "movd xmm5, [rbx];\n"                                                                                              \
    "movd xmm5, [rsp];\n"                                                                                              \
    "movd xmm5, [rbp];\n"                                                                                              \
    "movd xmm5, [rsi];\n"                                                                                              \
    "movd xmm5, [rdi];\n"                                                                                              \
    "movd xmm5, [r8d];\n"                                                                                              \
    "movd xmm5, [r9d];\n"                                                                                              \
    "movd xmm5, [r10];\n"                                                                                              \
    "movd xmm5, [r11];\n"                                                                                              \
    "movd xmm5, [r12];\n"                                                                                              \
    "movd xmm5, [r13];\n"                                                                                              \
    "movd xmm5, [r14];\n"                                                                                              \
    "movd xmm5, [r15];\n"                                                                                              \
    "movd xmm5, [eax+0xee];\n"                                                                                         \
    "movd xmm5, [ecx+0xdd];\n"                                                                                         \
    "movd xmm5, [edx+0x8efde];\n"                                                                                      \
    "movd xmm5, [ebx+0x4cd];\n"                                                                                        \
    "movd xmm5, [esp+0xaa];\n"                                                                                         \
    "movd xmm5, [ebp+0xff];\n"                                                                                         \
    "movd xmm5, [esi+0xfddd];\n"                                                                                       \
    "movd xmm5, [edi+0xabcd];\n"                                                                                       \
    "movd xmm5, [r8d+0x9a9a9];\n"                                                                                      \
    "movd xmm5, [r9d+0x456];\n"                                                                                        \
    "movd xmm5, [r10d+0x123];\n"                                                                                       \
    "movd xmm5, [r11d+0x89dd];\n"                                                                                      \
    "movd xmm5, [r12d+0x9a34];\n"                                                                                      \
    "movd xmm5, [r13d+0xffff];\n"                                                                                      \
    "movd xmm5, [r14d+0x4edf];\n"                                                                                      \
    "movd xmm5, [r15d+0xfe];\n"                                                                                        \
    "movd ebx, xmm5;\n"                                                                                                \
    "movd r14d, xmm5;\n"                                                                                               \
    ";\n"                                                                                                              \
    "movd xmm6, eax;\n"                                                                                                \
    "movd xmm6, ecx;\n"                                                                                                \
    "movd xmm6, edx;\n"                                                                                                \
    "movd xmm6, ebx;\n"                                                                                                \
    "movd xmm6, esp;\n"                                                                                                \
    "movd xmm6, ebp;\n"                                                                                                \
    "movd xmm6, esi;\n"                                                                                                \
    "movd xmm6, edi;\n"                                                                                                \
    "movd xmm6, r8d;\n"                                                                                                \
    "movd xmm6, r9d;\n"                                                                                                \
    "movd xmm6, r10d;\n"                                                                                               \
    "movd xmm6, r11d;\n"                                                                                               \
    "movd xmm6, r12d;\n"                                                                                               \
    "movd xmm6, r13d;\n"                                                                                               \
    "movd xmm6, r14d;\n"                                                                                               \
    "movd xmm6, r15d;\n"                                                                                               \
    "movd ebx, xmm6;\n"                                                                                                \
    "movd r14d, xmm6;\n"                                                                                               \
    ";\n"                                                                                                              \
    "movd xmm7, eax;\n"                                                                                                \
    "movd xmm7, ecx;\n"                                                                                                \
    "movd xmm7, edx;\n"                                                                                                \
    "movd xmm7, ebx;\n"                                                                                                \
    "movd xmm7, esp;\n"                                                                                                \
    "movd xmm7, ebp;\n"                                                                                                \
    "movd xmm7, esi;\n"                                                                                                \
    "movd xmm7, edi;\n"                                                                                                \
    "movd xmm7, r8d;\n"                                                                                                \
    "movd xmm7, r9d;\n"                                                                                                \
    "movd xmm7, r10d;\n"                                                                                               \
    "movd xmm7, r11d;\n"                                                                                               \
    "movd xmm7, r12d;\n"                                                                                               \
    "movd xmm7, r13d;\n"                                                                                               \
    "movd xmm7, r14d;\n"                                                                                               \
    "movd xmm7, r15d;\n"                                                                                               \
    "movd ebx, xmm7;\n"                                                                                                \
    "movd r14d, xmm7;\n"                                                                                               \
    ";\n"                                                                                                              \
    ";\n"                                                                                                              \
    "movd xmm8, eax;\n"                                                                                                \
    "movd xmm8, ecx;\n"                                                                                                \
    "movd xmm8, edx;\n"                                                                                                \
    "movd xmm8, ebx;\n"                                                                                                \
    "movd xmm8, esp;\n"                                                                                                \
    "movd xmm8, ebp;\n"                                                                                                \
    "movd xmm8, esi;\n"                                                                                                \
    "movd xmm8, edi;\n"                                                                                                \
    "movd xmm8, r8d;\n"                                                                                                \
    "movd xmm8, r9d;\n"                                                                                                \
    "movd xmm8, r10d;\n"                                                                                               \
    "movd xmm8, r11d;\n"                                                                                               \
    "movd xmm8, r12d;\n"                                                                                               \
    "movd xmm8, r13d;\n"                                                                                               \
    "movd xmm8, r14d;\n"                                                                                               \
    "movd xmm8, r15d;\n"                                                                                               \
    "movd ebx, xmm8;\n"                                                                                                \
    "movd r14d, xmm8;\n"                                                                                               \
    ";\n"                                                                                                              \
    "movd xmm9, eax;\n"                                                                                                \
    "movd xmm9, ecx;\n"                                                                                                \
    "movd xmm9, edx;\n"                                                                                                \
    "movd xmm9, ebx;\n"                                                                                                \
    "movd xmm9, esp;\n"                                                                                                \
    "movd xmm9, ebp;\n"                                                                                                \
    "movd xmm9, esi;\n"                                                                                                \
    "movd xmm9, edi;\n"                                                                                                \
    "movd xmm9, r8d;\n"                                                                                                \
    "movd xmm9, r9d;\n"                                                                                                \
    "movd xmm9, r10d;\n"                                                                                               \
    "movd xmm9, r11d;\n"                                                                                               \
    "movd xmm9, r12d;\n"                                                                                               \
    "movd xmm9, r13d;\n"                                                                                               \
    "movd xmm9, r14d;\n"                                                                                               \
    "movd xmm9, r15d;\n"                                                                                               \
    "movd ebx, xmm9;\n"                                                                                                \
    "movd r14d, xmm9;\n"                                                                                               \
    ";\n"                                                                                                              \
    "movd xmm10, eax;\n"                                                                                               \
    "movd xmm10, ecx;\n"                                                                                               \
    "movd xmm10, edx;\n"                                                                                               \
    "movd xmm10, ebx;\n"                                                                                               \
    "movd xmm10, esp;\n"                                                                                               \
    "movd xmm10, ebp;\n"                                                                                               \
    "movd xmm10, esi;\n"                                                                                               \
    "movd xmm10, edi;\n"                                                                                               \
    "movd xmm10, r8d;\n"                                                                                               \
    "movd xmm10, r9d;\n"                                                                                               \
    "movd xmm10, r10d;\n"                                                                                              \
    "movd xmm10, r11d;\n"                                                                                              \
    "movd xmm10, r12d;\n"                                                                                              \
    "movd xmm10, r13d;\n"                                                                                              \
    "movd xmm10, r14d;\n"                                                                                              \
    "movd xmm10, r15d;\n"                                                                                              \
    "movd ebx, xmm10;\n"                                                                                               \
    "movd r14d, xmm10;\n"                                                                                              \
    ";\n"                                                                                                              \
    ";\n"                                                                                                              \
    "movd xmm11, eax;\n"                                                                                               \
    "movd xmm11, ecx;\n"                                                                                               \
    "movd xmm11, edx;\n"                                                                                               \
    "movd xmm11, ebx;\n"                                                                                               \
    "movd xmm11, esp;\n"                                                                                               \
    "movd xmm11, ebp;\n"                                                                                               \
    "movd xmm11, esi;\n"                                                                                               \
    "movd xmm11, edi;\n"                                                                                               \
    "movd xmm11, r8d;\n"                                                                                               \
    "movd xmm11, r9d;\n"                                                                                               \
    "movd xmm11, r10d;\n"                                                                                              \
    "movd xmm11, r11d;\n"                                                                                              \
    "movd xmm11, r12d;\n"                                                                                              \
    "movd xmm11, r13d;\n"                                                                                              \
    "movd xmm11, r14d;\n"                                                                                              \
    "movd xmm11, r15d;\n"                                                                                              \
    "movd ebx, xmm11;\n"                                                                                               \
    "movd r14d, xmm11;\n"                                                                                              \
    ";\n"                                                                                                              \
    ";\n"                                                                                                              \
    "movd xmm11, [eax];\n"                                                                                             \
    "movd xmm11, [ecx];\n"                                                                                             \
    "movd xmm11, [edx];\n"                                                                                             \
    "movd xmm11, [ebx];\n"                                                                                             \
    "movd xmm11, [esp];\n"                                                                                             \
    "movd xmm11, [ebp];\n"                                                                                             \
    "movd xmm11, [esi];\n"                                                                                             \
    "movd xmm11, [edi];\n"                                                                                             \
    "movd xmm11, [r8d];\n"                                                                                             \
    "movd xmm11, [r9d];\n"                                                                                             \
    "movd xmm11, [r10d];\n"                                                                                            \
    "movd xmm11, [r11d];\n"                                                                                            \
    "movd xmm11, [r12d];\n"                                                                                            \
    "movd xmm11, [r13d];\n"                                                                                            \
    "movd xmm11, [r14d];\n"                                                                                            \
    "movd xmm11, [r15d];\n"                                                                                            \
    "movd xmm11, [eax+0xee];\n"                                                                                        \
    "movd xmm11, [ecx+0xdd];\n"                                                                                        \
    "movd xmm11, [edx+0x8efde];\n"                                                                                     \
    "movd xmm11, [ebx+0x4cd];\n"                                                                                       \
    "movd xmm11, [esp+0xaa];\n"                                                                                        \
    "movd xmm11, [ebp+0xff];\n"                                                                                        \
    "movd xmm11, [esi+0xfddd];\n"                                                                                      \
    "movd xmm11, [edi+0xabcd];\n"                                                                                      \
    "movd xmm11, [r8d+0x9a9a9];\n"                                                                                     \
    "movd xmm11, [r9d+0x456];\n"                                                                                       \
    "movd xmm11, [r10d+0x123];\n"                                                                                      \
    "movd xmm11, [r11d+0x89dd];\n"                                                                                     \
    "movd xmm11, [r12d+0x9a34];\n"                                                                                     \
    "movd xmm11, [r13d+0xffff];\n"                                                                                     \
    "movd xmm11, [r14d+0x4edf];\n"                                                                                     \
    "movd xmm11, [r15d+0xfe];\n"                                                                                       \
    "movd [ebx+0x4cd], xmm11;\n"                                                                                       \
    "movd [r14d+0x4edf], xmm11;\n"                                                                                     \
    ";\n"                                                                                                              \
    "movd xmm12, eax;\n"                                                                                               \
    "movd xmm12, ecx;\n"                                                                                               \
    "movd xmm12, edx;\n"                                                                                               \
    "movd xmm12, ebx;\n"                                                                                               \
    "movd xmm12, esp;\n"                                                                                               \
    "movd xmm12, ebp;\n"                                                                                               \
    "movd xmm12, esi;\n"                                                                                               \
    "movd xmm12, edi;\n"                                                                                               \
    "movd xmm12, r8d;\n"                                                                                               \
    "movd xmm12, r9d;\n"                                                                                               \
    "movd xmm12, r10d;\n"                                                                                              \
    "movd xmm12, r11d;\n"                                                                                              \
    "movd xmm12, r12d;\n"                                                                                              \
    "movd xmm12, r13d;\n"                                                                                              \
    "movd xmm12, r14d;\n"                                                                                              \
    "movd xmm12, r15d;\n"                                                                                              \
    "movd ebx, xmm12;\n"                                                                                               \
    "movd r14d, xmm12;\n"                                                                                              \
    ";\n"                                                                                                              \
    "movd xmm13, eax;\n"                                                                                               \
    "movd xmm13, ecx;\n"                                                                                               \
    "movd xmm13, edx;\n"                                                                                               \
    "movd xmm13, ebx;\n"                                                                                               \
    "movd xmm13, esp;\n"                                                                                               \
    "movd xmm13, ebp;\n"                                                                                               \
    "movd xmm13, esi;\n"                                                                                               \
    "movd xmm13, edi;\n"                                                                                               \
    "movd xmm13, r8d;\n"                                                                                               \
    "movd xmm13, r9d;\n"                                                                                               \
    "movd xmm13, r10d;\n"                                                                                              \
    "movd xmm13, r11d;\n"                                                                                              \
    "movd xmm13, r12d;\n"                                                                                              \
    "movd xmm13, r13d;\n"                                                                                              \
    "movd xmm13, r14d;\n"                                                                                              \
    "movd xmm13, r15d;\n"                                                                                              \
    "movd ebx, xmm13;\n"                                                                                               \
    "movd r14d, xmm13;\n"                                                                                              \
    ";\n"                                                                                                              \
    "movd xmm14, eax;\n"                                                                                               \
    "movd xmm14, ecx;\n"                                                                                               \
    "movd xmm14, edx;\n"                                                                                               \
    "movd xmm14, ebx;\n"                                                                                               \
    "movd xmm14, esp;\n"                                                                                               \
    "movd xmm14, ebp;\n"                                                                                               \
    "movd xmm14, esi;\n"                                                                                               \
    "movd xmm14, edi;\n"                                                                                               \
    "movd xmm14, r8d;\n"                                                                                               \
    "movd xmm14, r9d;\n"                                                                                               \
    "movd xmm14, r10d;\n"                                                                                              \
    "movd xmm14, r11d;\n"                                                                                              \
    "movd xmm14, r12d;\n"                                                                                              \
    "movd xmm14, r13d;\n"                                                                                              \
    "movd xmm14, r14d;\n"                                                                                              \
    "movd xmm14, r15d;\n"                                                                                              \
    "movd ebx, xmm14;\n"                                                                                               \
    "movd r14d, xmm14;\n"                                                                                              \
    ";\n"                                                                                                              \
    "movd xmm15, eax;\n"                                                                                               \
    "movd xmm15, ecx;\n"                                                                                               \
    "movd xmm15, edx;\n"                                                                                               \
    "movd xmm15, ebx;\n"                                                                                               \
    "movd xmm15, esp;\n"                                                                                               \
    "movd xmm15, ebp;\n"                                                                                               \
    "movd xmm15, esi;\n"                                                                                               \
    "movd xmm15, edi;\n"                                                                                               \
    "movd xmm15, r8d;\n"                                                                                               \
    "movd xmm15, r9d;\n"                                                                                               \
    "movd xmm15, r10d;\n"                                                                                              \
    "movd xmm15, r11d;\n"                                                                                              \
    "movd xmm15, r12d;\n"                                                                                              \
    "movd xmm15, r13d;\n"                                                                                              \
    "movd xmm15, r14d;\n"                                                                                              \
    "movd xmm15, r15d;\n"                                                                                              \
    "movd ebx, xmm15;\n"                                                                                               \
    "movd r14d, xmm15;\n"                                                                                              \
    ";\n"                                                                                                              \
    ""
