#define CODE                                                                                                           \
    "shrd rax, rax, 0;\n"                                                                                              \
    "shrd rax, rax, 1;\n"                                                                                              \
    "shrd rax, rax, 2;\n"                                                                                              \
    "shrd rax, rax, 3;\n"                                                                                              \
    "shrd rax, rax, 4;\n"                                                                                              \
    "shrd rax, rax, 5;\n"                                                                                              \
    "shrd rax, rax, 6;\n"                                                                                              \
    "shrd rax, rax, 7;\n"                                                                                              \
    "shrd rax, rax, 8;\n"                                                                                              \
    "shrd rax, rax, 9;\n"                                                                                              \
    "shrd rax, rax, 10;\n"                                                                                             \
    "shrd rax, rax, 11;\n"                                                                                             \
    "shrd rax, rax, 12;\n"                                                                                             \
    "shrd rax, rax, 13;\n"                                                                                             \
    "shrd rax, rax, 14;\n"                                                                                             \
    "shrd rax, rax, 15;\n"                                                                                             \
    "shrd rax, rbx, 16;\n"                                                                                             \
    "shrd rax, rbx, 17;\n"                                                                                             \
    "shrd rax, rbx, 18;\n"                                                                                             \
    "shrd rax, rbx, 19;\n"                                                                                             \
    "shrd rax, rbx, 20;\n"                                                                                             \
    "shrd rax, rbx, 21;\n"                                                                                             \
    "shrd rax, rbx, 22;\n"                                                                                             \
    "shrd rax, rbx, 23;\n"                                                                                             \
    "shrd rax, rbx, 24;\n"                                                                                             \
    "shrd rax, rbx, 25;\n"                                                                                             \
    "shrd rax, rbx, 26;\n"                                                                                             \
    "shrd rax, rbx, 27;\n"                                                                                             \
    "shrd rax, rbx, 28;\n"                                                                                             \
    "shrd rax, rbx, 29;\n"                                                                                             \
    "shrd rax, rbx, 30;\n"                                                                                             \
    "shrd rax, rbx, 31;\n"                                                                                             \
    "shrd rax, rcx, 32;\n"                                                                                             \
    "shrd rax, rcx, 33;\n"                                                                                             \
    "shrd rax, rcx, 34;\n"                                                                                             \
    "shrd rax, rcx, 35;\n"                                                                                             \
    "shrd rax, rcx, 36;\n"                                                                                             \
    "shrd rax, rcx, 37;\n"                                                                                             \
    "shrd rax, rcx, 38;\n"                                                                                             \
    "shrd rax, rcx, 39;\n"                                                                                             \
    "shrd rax, rcx, 40;\n"                                                                                             \
    "shrd rax, rcx, 41;\n"                                                                                             \
    "shrd rax, rcx, 42;\n"                                                                                             \
    "shrd rax, rcx, 43;\n"                                                                                             \
    "shrd rax, rcx, 44;\n"                                                                                             \
    "shrd rax, rcx, 45;\n"                                                                                             \
    "shrd rax, rcx, 46;\n"                                                                                             \
    "shrd rax, rcx, 47;\n"                                                                                             \
    "shrd rax, rdx, 48;\n"                                                                                             \
    "shrd rax, rdx, 49;\n"                                                                                             \
    "shrd rax, rdx, 50;\n"                                                                                             \
    "shrd rax, rdx, 51;\n"                                                                                             \
    "shrd rax, rdx, 52;\n"                                                                                             \
    "shrd rax, rdx, 53;\n"                                                                                             \
    "shrd rax, rdx, 54;\n"                                                                                             \
    "shrd rax, rdx, 55;\n"                                                                                             \
    "shrd rax, rdx, 56;\n"                                                                                             \
    "shrd rax, rdx, 57;\n"                                                                                             \
    "shrd rax, rdx, 58;\n"                                                                                             \
    "shrd rax, rdx, 59;\n"                                                                                             \
    "shrd rax, rdx, 60;\n"                                                                                             \
    "shrd rax, rdx, 61;\n"                                                                                             \
    "shrd rax, rdx, 62;\n"                                                                                             \
    "shrd rax, rdx, 63;\n"                                                                                             \
    "shrd r10, r11, 51;\n"                                                                                             \
    "shrd r12, r15, 51;\n"                                                                                             \
    "shrd r12, r8, 51;\n"                                                                                              \
    "shrd r12, rbx, 51;\n"                                                                                             \
    "shrd r12, rdx, 51;\n"                                                                                             \
    "shrd r14, rcx, 51;\n"                                                                                             \
    "shrd r15, rbp, 51;\n"                                                                                             \
    "shrd r8, r13, 51;\n"                                                                                              \
    "shrd r8, rcx, 51;\n"                                                                                              \
    "shrd r8, rdx, 51;\n"                                                                                              \
    "shrd r9, r8, 51;\n"                                                                                               \
    "shrd rax, rbp, 51;\n"                                                                                             \
    "shrd rbp, r15, 51;\n"                                                                                             \
    "shrd rcx, r8, 51;\n"                                                                                              \
    ""
