#define CODE                                                                                                           \
    "mov eax, 0x2;\n"                                                                                                  \
    "mov eax, 0x7f;\n"                                                                                                 \
    "mov eax, 0x80;\n"                                                                                                 \
    "mov eax, 0x80;\n"                                                                                                 \
    "mov eax, 0xff;\n"                                                                                                 \
    "mov eax, 0x7ff;\n"                                                                                                \
    "mov esi, 0x2;\n"                                                                                                  \
    "mov esi, 0x7f;\n"                                                                                                 \
    "mov esi, 0x80;\n"                                                                                                 \
    "mov esi, 0x80;\n"                                                                                                 \
    "mov esi, 0xff;\n"                                                                                                 \
    "mov esi, 0x7ff;\n"                                                                                                \
    "mov esi, 0x2;\n"                                                                                                  \
    "mov esi, 0x7f;\n"                                                                                                 \
    "mov esi, 0x80;\n"                                                                                                 \
    "mov esi, 0x80;\n"                                                                                                 \
    "mov esi, 0xff;\n"                                                                                                 \
    "mov esi, 0x7ff;\n"                                                                                                \
    "mov r13d, 0x2;\n"                                                                                                 \
    "mov r13d, 0x7f;\n"                                                                                                \
    "mov r13d, 0x80;\n"                                                                                                \
    "mov r13d, 0x80;\n"                                                                                                \
    "mov r13d, 0xff;\n"                                                                                                \
    "mov r13d, 0x7ff;\n"                                                                                               \
    "mov r15w, 0x2;\n"                                                                                                 \
    "mov r15w, 0x7f;\n"                                                                                                \
    "mov r15w, 0x80;\n"                                                                                                \
    "mov r15w, 0x80;\n"                                                                                                \
    "mov r15w, 0xff;\n"                                                                                                \
    "mov r15w, 0x7ff;\n"                                                                                               \
    "mov r15b, -0x2;\n"                                                                                                \
    "mov r15b, 0x2;\n"                                                                                                 \
    "mov r15b, 0x7f;\n"                                                                                                \
    "mov r15b, 0x80;\n"                                                                                                \
    "mov r15b, 0x80;\n"                                                                                                \
    "mov r15b, 0xff;\n"                                                                                                \
    "mov r10b, -0x2;\n"                                                                                                \
    "mov r11b, -0x2;\n"                                                                                                \
    "mov r12b, -0x2;\n"                                                                                                \
    "mov al, -0x2;\n"                                                                                                  \
    "mov al, -0x1;\n"                                                                                                  \
    "mov al, 0x1;\n"                                                                                                   \
    "mov cl, -0x2;\n"                                                                                                  \
    "mov cl, -0x1;\n"                                                                                                  \
    "mov cl, 0x1;\n"                                                                                                   \
    "mov ax, -0x2;\n"                                                                                                  \
    "mov ax, -0x1;\n"                                                                                                  \
    "mov ax, 0x1;\n"                                                                                                   \
    "mov cx, -0x2efd;\n"                                                                                               \
    "mov cx, -0x2efa;\n"                                                                                               \
    "mov cx, 0x2efa;\n"                                                                                                \
    "mov si, -0x2efd;\n"                                                                                               \
    "mov si, -0x2efa;\n"                                                                                               \
    "mov si, 0x2efa;\n" 
