#define CODE                                                                                                           \
    "not al;\n"                                                                                                        \
    "not cl;\n"                                                                                                        \
    "not dl;\n"                                                                                                        \
    "not bl;\n"                                                                                                        \
    "not spl;\n"                                                                                                       \
    "not bpl;\n"                                                                                                       \
    "not sil;\n"                                                                                                       \
    "not dil;\n"                                                                                                       \
    "not r8b;\n"                                                                                                       \
    "not r9b;\n"                                                                                                       \
    "not r10b;\n"                                                                                                      \
    "not r11b;\n"                                                                                                      \
    "not r12b;\n"                                                                                                      \
    "not r13b;\n"                                                                                                      \
    "not r14b;\n"                                                                                                      \
    "not r15b;\n"                                                                                                      \
    "not rax;\n"                                                                                                       \
    "not rbx;\n"                                                                                                       \
    "not rcx;\n"                                                                                                       \
    "not rdx;\n"                                                                                                       \
    "not rdi;\n"                                                                                                       \
    "not r8;\n"                                                                                                        \
    "not r9;\n"                                                                                                        \
    "not r10;\n"                                                                                                       \
    "not r11;\n"                                                                                                       \
    "not r12;\n"                                                                                                       \
    "not r13;\n"                                                                                                       \
    "not r14;\n"                                                                                                       \
    "not r15;\n"                                                                                                       \
    "not rsp;\n"                                                                                                       \
    "not rsi;\n"                                                                                                       \
    "not rbp;\n"                                                                                                       \
    ""
