.TH ASMLINE 1 2021-09-19 GNU

.SH NAME
asmline \- assemblyline tool 

.SH SYNOPSIS
.B asmline
[\fB\-r\fR]
[\fB\-p\fR]
[\fB\-c\fR \fICHUNK_SIZE>1\fR]
[\fB\-o\fR \fIFILENAME\fR]
[\fB\-n\fR]
[\fB\-s\fR]
[\fB\-m\fR]
[\fB\-h\fR]
[\fB\-v\fR]
path/to/file.asm

.SH DESCRIPTION
.B asmline 
Generates machine code from a file or stdin containing x64 assembly instructions. 

.br
Machine code could be executed directly without the need for an executable file format. 
.br
Obtain command-line instructions for generating an ELF binary file from assembly code.

.SH OPTIONS
.TP
.BR \-r ", " \-\-return
executes assembly code and prints out the contents of the rax register (return register).
.TP
.BR \-p ", " \-\-print
when assembling path/to/file.asm the corresponding machine code will be printed to stdout.
.TP
.BR \-c ", " \-\-chunk " " \fICHUNK_SIZE>1
sets a given CHUNK_SIZE boundary in bytes. Nop padding will be used to ensure 
.br
no instruction opcode will cross the specified CHUNK_SIZE boundary.
.TP
.BR \-o ", " \-\-object " " \fIFILENAME
generates a binary file from path/to/file.asm called FILENAME.bin in the current directory.
.TP
.BR \-n ", " \-\-nasm
enables nasm-style mov-immediate register-size optimization.
.br
ex: if immediate size for mov is less than or equal to max signed 32 bit assemblyline 
.br
    will emit code to mov to 32-bit register rather than 64-bit.
.br
That is: "mov rax, 0x7fffffff" as "mov eax, 0x7fffffff" -> b8 ff ff ff 7f
.TP
.BR \-s ", " \-\-strict
disables nasm-style mov-immediate register-size optimization.
.br
ex: even if immediate size for mov is less than or equal to max signed 32 bit assemblyline 
.br
    will pad the immediate to fit 64bit.
.br
That is: "mov rax,0x7fffffff" as "mov rax,0x000000007fffffff" 
.br
          -> 48 b8 ff ff ff 7f 00 00 00 00
.TP
.BR \-m ", " \-\-manual
assemblyline will check the immediate value for leading 0's and thus allows manual
.br 
optimizations. This is currently set as default.
.br
ex: "mov rax, 0x000000007fffffff" ->  48 b8 ff ff ff 7f 00 00 00 00
.br
    "mov rax, 0x7fffffff" -> b8 ff ff ff 7f
.TP
.BR \-h ", " \-\-help
prints usage information to stdout and exits.
.TP
.BR \-v ", " \-\-version
prints version information to stdout and exits.
