name: Make check

on: [ push ]

jobs:
  build:
    runs-on: ubuntu-latest

    name: Build and test

    steps:
    - uses: actions/checkout@v3

    - name: install nasm
      run: sudo apt install -y nasm

    - name: autogen
      run: ./autogen.sh

    - name: configure
      run: ./configure

    - name: make
      run: make

    - name: make check
      run: make check
